### ISSUE TITLE
changeCobraSolver avoid global variables

### ISSUE THREAD

**Issue by AndrasHartmann** [opencobra/cobratoolbox#100]
Hi,

I am using Cobra together with parallel toolbox, and the standard in this setting global variables do not get passed from the MATLAB client to the workers. Thus, in every thread the global variables have to be set, e.g. I have to call changeCobraSolver. I think there could be an alternative mechanism for changeCobraSolver which also suits parallel computing.

**Comment by tpfau** [comment]
The only way I currently see would be to provide an option to select the solver during the call to optimizeCbModel (and all other functions which use solveCobraLP/MILP/...), which would be a lot of code that needs to be altered. 
Just one thing though:
Most solvers do possess internal parallelisation methods, so it is not always advisable to actually run them on very few cores (or even only one core), as they might end up being much slower.
E.g. CPLEX will by default always run one simplex instance and fill the remaining available cores with barrier methods, thus, depending on how fast the barrier instances reach the objective, it can happen that there is no speedup at all (if simplex is faster than the barrier runs) or, that two processors are e.g. 10 times fast than one, depending on the problem.

**Comment by laurentheirendt** [comment]
Thanks @AndrasHartmann. As discussed with @syarra, we might be looking into implementing an option of writing the global variables to a file when using multiple workers.

**Comment by laurentheirendt** [comment]
Issue solved in new version of `changeCobraSolver()`. This:
```Matlab
initCobraToolbox
global CBT_LP_SOLVER
parpool(2);
parfor i = 1:2
   CBT_LP_SOLVER
end
```
now yields:
```
CBT_LP_SOLVER =
glpk
CBT_LP_SOLVER =
glpk
>> 
```
Thanks @AndrasHartmann for reporting this issue.
