### ISSUE TITLE
identifyCorrelSets outputs sets of size = 1

### ISSUE THREAD

**Issue by alyamahmoud** [opencobra/cobratoolbox#101]
I am trying to use identifyCorrelSets to compute cosets and I am getting cosets of size = 1 independent of the threshold used. What do these cosets mean ?

**Comment by laurentheirendt** [comment]
@alyamahmoud , may we close this issue?

**Comment by tpfau** [comment]
If this still persist, please open a new issue and provide an example of your input data. We will close this for now, as we can't currently reproduce the situation

**Comment by laurentheirendt** [comment]
I agree with @tpfau. Thanks @alyamahmoud.
