### ISSUE TITLE
CHRR bug with Recon2

### ISSUE THREAD

**Issue by marouenbg** [opencobra/cobratoolbox#1059]
*Please include a short description of problem here*
While the CHRR sampling algorithm works fine in the following setting:
`load Recon2.0model.mat;
changeCobraSolver('ibm_cplex');
[samples,p,min,max]=chrrSampler(Recon2model,1000,1000,0);`
It fails with the following call
`[samples,p,min,max]=chrrSampler(Recon2model,1000,1000,1)`

I get the error

`Error using preprocess>getCCcenter (line 144)
Could not solve the LP, consult the information above.
Error in preprocess (line 89)
        [x0,dist] = getCCcenter(P.A,P.b);
Error in chrrSampler (line 136)
    [roundedPolytope] = preprocess(P, toRound);`

The last argument corresponds to `toRound` which means in the function description `to round the polytope before sampling`. I understand from the paper that the added value of the method is the rounding of the polytope to avoid non-uniform regions that can bias the sampling towards certain values.
cc @ithiele 

**I hereby confirm that I have:**

- [x] Tried to solve the issue on my own
- [x] Retried to run my code with the latest version of The COBRA Toolbox
- [x] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

**Comment by laurentheirendt** [comment]
@Bounciness, may you look into this? Thanks 👍

**Comment by Bounciness** [comment]
Looking into this, get back to you soon.

**Comment by marouenbg** [comment]
The code works fine with the defaults with glpk, while with IBM CPLEX, I had to increase the CBT feasibility tolerance to get the sampling running. This relates to a previous [issue](https://github.com/opencobra/cobratoolbox/pull/928).
