### ISSUE TITLE
Issue About getDistributedModelFolder

### ISSUE THREAD

**Issue by mikeaalv** [opencobra/cobratoolbox#1070]
*Please include a short description of problem here*

**I hereby confirm that I have:**

- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

I am trying to install the cobra toolbox on a linux sever. After I use initCobraToolbo, I got:

Checking if git is installed ...  Done.
 > Checking if the repository is tracked using git ...  Done.
 > Checking if curl is installed ...  Done.
 > Checking if remote can be reached ...  Done.
 > Initializing and updating submodules (this may take a while)... Done.
 > Adding all the files of The COBRA Toolbox ...  Done.
 > Define CB map output... set to svg.
Error using getDistributedModelFolder (line 36)
Requested Model not present in the model directory.\n This is either due to the
model not being downloaded, or not being part of the distributed models.

Error in initCobraToolbox (line 255)
    xmlTestFile = [getDistributedModelFolder(xmlTestModel) filesep
    xmlTestModel];

I am not sure what is happening and I have install cobra toolbox in my computer long time ago from which I didn't see this error.

On the linux machine, I have no root. Would that be related?

Thanks.

**Comment by laurentheirendt** [comment]
@mikeaalv, thanks for reporting this. You do not need to have `root` access to install the COBRA Toolbox. This is a machine-specific configuration issue.

May you post these issues in our [forum](https://groups.google.com/forum/#!forum/cobra-toolbox) for a faster turnaround? Thanks. 👍

**Comment by mikeaalv** [comment]
Sure. Thanks for your suggestions.
