### ISSUE TITLE
Crash when "initCobraToolbox"

### ISSUE THREAD

**Issue by juanvillada** [opencobra/cobratoolbox#1076]
Hi!

My setup is:

```
OS: macOS High Sierra
Matlab: 2016b
```
### Issue:
I was having a complete crash of `Matlab` when running `initCobraToolbox` after installation of the latest COBRA version. The crash occurred immediately after printing:

```
>Checking available solvers and solver interfaces ... Done.
```

### I solved the issue by doing this:
I traced the issue back and it seems related to the `changeCobraSolver.m` file. I tried all the versions in the history and the file in the link below was the most recent version when the issue does not happen.

https://github.com/opencobra/cobratoolbox/commit/13b011e858a85ee959c1f322f45138f61bde2d7f#diff-8cb2ec253ae1557aa0bc7ded609595f5

I replaced the lastest version of `changeCobraSolver.m` for the one in the link and everything is working fine (all other files are from the most recent version of COBRA). However, versions after _Nov 8 2017_ of `changeCobraSolver.m` generate complete crash of Matlab.

I hope this can be useful for someone with the same set up as ours,

Best!

**I hereby confirm that I have:**

- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

**Comment by tpfau** [comment]
Hi,

Thanks for reporting this issue. It is likely due to incompatible mex files, as the change that causes your issue was when we actually started testing whether a solver works on the os. If we can figure out, which solver causes the issue, we could add a incompatability marker to it.

Could you let us know, which solvers you have installed on your machine, or use a recent version and add a breakpoint at `changeCobraSolver` in the first eval line of the following snipet (around line 410 in `changeCobraSolver`:
```Matlab
if solverOK    
    eval(['oldval = CBT_', solverType, '_SOLVER;']);
    eval(['CBT_', solverType, '_SOLVER = solverName;']);
    Problem = struct('A',0,'b',0,'c',1,'osense',-1,'F',1,'lb',0,'ub',0,'csense','E','vartype','C','x0',0);
    try
        eval(['solveCobra' solverType '(Problem,''printLevel'', 0);'])
    catch ME
        solverOK = false;
        eval(['CBT_', solverType, '_SOLVER = oldval;']);
    end    
end
```
Then we would know, which solver causes the issue and could likely adapt our checks.

**Comment by juanvillada** [comment]
Hi @tpfau! Thanks for your attention.

`cobratoolbox` recognises these solvers in my system:

- [---*] ILOG_CPLEX_PATH
- [*---] GUROBI_PATH
- [---*] TOMLAB_PATH
- [-*--] MOSEK_PATH

The latest `changeCobraSolver` in the GitHub Repo has this code (L398-413):

```matlab
% set solver related global variables
if solverOK
    cwarn = warning;
    warning('off');
    eval(['oldval = CBT_', solverType, '_SOLVER;']);
    eval(['CBT_', solverType, '_SOLVER = solverName;']);
    Problem = struct('A',[0 1],'b',0,'c',[1;1],'osense',-1,'F',speye(2),'lb',[0;0],'ub',[0;0],'csense','E','vartype',['C';'I'],'x0',[0;0]);
    try
        evalc(['solveCobra' solverType '(Problem,''printLevel'', 0);']);
    catch ME
        solverOK = false;
        eval(['CBT_', solverType, '_SOLVER = oldval;']);
    end
    warning(cwarn)
end
end
```

 I replaced my `changeCobraSolver` by the latest version. When the breakpoint was added to the latest version of `changeCobraSolver` and I ran `initCobraToolbox`, I observed this:

- minos **OK**
- glpk **OK**
- gurobi **OK**
- ibm_cplex **CRASH!**

Then I double-checked and the `ibm_cplex` link was corrupted. I reinstalled `ibm_cplex` and added the right path to `matlab`. I initialised again `cobratoolbox` with `initCobraToolbox` and tested it using `testAll`.  **It is working well now!**

Thank you so much @tpfau!

**Comment by tpfau** [comment]
Thats actually what I expected.
IBM Cplex and High Sierra have had a couple of issues, and (from what I can say), there are still quite some problems between CPLEX and Matlab 2017b (at least till cplex 12.7.1). 
Great that you could solve it though :)

**Comment by laurentheirendt** [comment]
@juanvillada, thanks for reporting this issue.

We will complete [this compatibility matrix](https://github.com/opencobra/cobratoolbox/blob/master/docs/source/installation/compatMatrix.md) soon, especially for High Sierra. Any help is welcome here.
