### ISSUE TITLE
createModel should create osenseStr field and not model.osense

### ISSUE THREAD

**Issue by rmtfleming** [opencobra/cobratoolbox#1078]
*Please include a short description of problem here*

**I hereby confirm that I have:**

- [] Tried to solve the issue on my own
- [] Retried to run my code with the latest version of The COBRA Toolbox
- [] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

**Comment by tpfau** [comment]
Can be closed

**Comment by laurentheirendt** [comment]
Thanks 👍
