### ISSUE TITLE
optimizeCbModel

### ISSUE THREAD

**Issue by hscotthinton** [opencobra/cobratoolbox#108]
optimizeCbModel is not working on the latest download. I get the following error

Output argument "FBAsolution" (and maybe others) not assigned during
call to "optimizeCbModel".
Error in robustnessAnalysis (line 44)
    solMin = optimizeCbModel(tmpModel,'min');
Error in AerobicGlucoseBioMassRA (line 20)
[controlFlux, objFlux] = robustnessAnalysis(model,'EX_o2(e)',100) 

It works on the previous download

**Comment by mlehoai** [comment]
Dear hscotthinton,

We have fixed it and updated the function.
Please let us know if the problem persists.

Regards,

Minh Le

**Comment by hscotthinton** [comment]
Is there a place to just download the function instead of having to download the whole toolbox? Thanks.
                Scott

**Comment by mlehoai** [comment]
Dear Scott,
I suggest that you use a git software for this purpose. For example
https://git-scm.com/

Regards,

Minh Le

**Comment by hscotthinton** [comment]
Thanks!!

Sent from my iPhone

On Jan 30, 2016, at 11:42 AM, Minh Le <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Scott,
I suggest that you use a git software for this purpose. For example
https://git-scm.com/

Regards,

Minh Le

**Comment by laurentheirendt** [comment]
@hscotthinton , may we close this issue?
