### ISSUE TITLE
ReadSBML does not replace LPAREN RPAERN with ( )

### ISSUE THREAD

**Issue by akaviaLab** [opencobra/cobratoolbox#1089]
readSBML (when called as part of readCbModel) does not replace LPAREN with ( or RPAREN with ).

I noticed this after updating to Cobra 3.0 and trying to reload an XML file for Recon 2.2 (MODEL1603150001.xml downloaded from the BioModels database http://www.ebi.ac.uk/biomodels-main/MODEL1603150001).

I'm not sure when and why the change happened. This is an easy fix, but I'm opening an issue since this might have been replaced for a specific reason and/or the SBML standard changed (or has something to say about this). If there's no specific reason, I'll add a pull request with most of 
deprecated/_io_depreciated/convertSBMLToCobra_Depreciated.m: cleanUpFormatting.

**I hereby confirm that I have:**

- [x] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

**Comment by tpfau** [comment]
We are currently facing the issue on how to interpret SBML IDs in the toolbox.
It is a general problem, that COBRA IDs and SBML IDs have different rules wrt allowed characters as different software tools use different ways to encode changes in IDs. 
This is also being discussed in opencobra/schema in issues [6](https://github.com/opencobra/schema/issues/6) and [8](https://github.com/opencobra/schema/issues/8) and I would suggest to use those threads for the discussion.

**Comment by tpfau** [comment]
This should be solved.

**Comment by laurentheirendt** [comment]
Thanks 👍
