### ISSUE TITLE
optKnock

### ISSUE THREAD

**Issue by hscotthinton** [opencobra/cobratoolbox#111]
There seems to be aproblem with optKnock. If I run the example code from the cobra protocol

model = readCbModel('ecoli_textbook');
model = changeRxnBounds(model, {'EX_o2(e)', 'EX_glc(e)'}, [0 -20], 'l');
selectedRxns = {model.rxns{ [1, 3:5, 7:8, 10, 12, 15:16, 18, 40:41, 44, 46, 48:49, 51, 53:55, 57, 59:62, 64:68, 71:77, 79:83, 85:86, 89:95]}};

options.targetRxn = 'EX_lac-D(e)'; 
options.vMax = 1000; 
options.numDel = 5; 
options.numDelSense = 'L';
constrOpt.rxnList = {'Biomass_Ecoli_core_N(w/GAM)-Nmet2', 'ATPM'}; 
constrOpt.values = [0.05, 8.39]; 
constrOpt.sense = 'GE'; 
optKnockSol = OptKnock(model, selectedRxns, options, constrOpt);

I get the following error messages

Expected one output from a curly brace or dot indexing expression, but
there were 0 results.
Error in OptKnock (line 142)
targetRxnIDirrev = rev2irrev{targetRxnID}(1);
Error in optKnock_test (line 14)
optKnockSol = OptKnock(model, selectedRxns, options, constrOpt);

**Comment by hscotthinton** [comment]
The problem seems to be with the setConstraintsIrrevModel.m function. If it is replaced by an older version it works

**Comment by hscotthinton** [comment]
This is only a problem with gurobi, it work fine with tomlab_cplex

**Comment by Kalaivani93** [comment]
How do I get Tomlab_cplex

**Comment by hscotthinton** [comment]
Tomlab_cplex is commercial software. See http://tomopt.com/tomlab/products/cplex/

**Comment by laurentheirendt** [comment]
Closing as instructions for Tomlab added in PR #325 .
