### ISSUE TITLE
Slightly confusing description of host organization in createMultipleSpeciesModel

### ISSUE THREAD

**Issue by bbarker** [opencobra/cobratoolbox#1117]
Hi there,

I find the [description](https://opencobra.github.io/cobratoolbox/latest/modules/analysis/multiSpecies/index.html?highlight=createmultiplespeciesmodel#src.analysis.multiSpecies.createMultipleSpeciesModel) for `createMultipleSpeciesModel` a bit difficult to parse, in particular:

> Creates a common space u (lumen) through which all cells can feed and exchange metabolites, and separate extracellular spaces for all joined models. If a host model is entered, a separate compartment b (body fluids) which has no connection to extracellular space is created for the host. Metabolites can be transported from the lumen to e, from e to the cytosol and from the cytosol to b, but not from body fluids to the lumen.

I don't think I can visualize a sensible "topology" of the various compartments from this description, and trying to explain why I can't would only further the confusion, as there are many possible contingencies to go through. 

Would it be possible to add a drawing to the documentation in some form? I'll even make a drawing, if you just want to sketch out something on a piece of paper and snapshot it here! That is a fair price for understanding :-).

Additionally, I'll say that I searched in the referenced article *Klitgord and Segre 2010, PMID 21124952* and did not find mention of host body fluids - why is it unreasonable to assume (given there is a lumen) that the host cell is just another cell embedded in the lumen compartment?

**I hereby confirm that I have:**

- [x] Tried to solve the issue on my own
- [NA] Retried to run my code with the latest version of The COBRA Toolbox
- [x] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

**Comment by almut-heinken** [comment]
Hello,
the setup in the createMultipleSpeciesModel function is a modification of the setup in Klitgord and Segre. 2010 It was first used in Heinken et al., Gut Microbes 2013, and is depicted in the following image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3555882/figure/F2/
As you can see, the host cell (if entered) is connected to the lumen compartment but also has a separate body fluids compartment. If no host is entered, there is only a lumen compartment as an inlet for a simulated diet/medium connecting all joined microbe models.
I hope this helps,
best regards
Almut

**Comment by JoanSong** [comment]
Hello,

It seems that in the picture, there is no extracellular compartment for the host. Is this true for the createMultipleSpeciesModel function? 

Thank you!
Jo

**Comment by almut-heinken** [comment]
@JoanSong
no, the host also has its own extracellular compartment through which it can take up metabolites from the lumen.
Best regards,
Almut

**Comment by laurentheirendt** [comment]
Thanks @JoanSong and @almut-heinken 👍

**Comment by hariszaf** [comment]
Hi there, 

is it by any chance the correct PMID [here](https://github.com/opencobra/cobratoolbox/blob/master/src/analysis/multiSpecies/microbiomeModelingToolbox/pairwiseInteractionModeling/createMultipleSpeciesModel.m#L8) is not the one mentioned but
the [3555882](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc3555882/) ([doi.org/10.4161/gmic.22370](https://doi.org/10.4161/gmic.22370))?
