### ISSUE TITLE
getGroupVectorFromInchi seems to be defined twice

### ISSUE THREAD

**Issue by akaviaLab** [opencobra/cobratoolbox#1128]
There are two files that contain the source for getGroupVectorFromInchi
src/analysis/thermo/groupContribution/getGroupVectorFromInchi.m src/analysis/thermo/componentContribution/getGroupVectorFromInchi.m

There are some differences between them, but I think they can be unified. If not, perhaps one of them or both can be renamed?

**I hereby confirm that I have:**

- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

**Comment by tpfau** [comment]
They are the same (except for an optional debugging argument and a comment.
@rmtfleming would it be ok to remove the one from the componentContribution folder?
