### ISSUE TITLE
removeGitIgnoredNewFiles seems to crash on my Mac

### ISSUE THREAD

**Issue by akaviaLab** [opencobra/cobratoolbox#1130]
When running testAll, removeGitIgnoredNewFIles crashes
Error using cell/setdiff>cellsetdiffR2012a (line 291)
Input A of class cell and input B of class struct must be cell arrays of character
vectors, unless one is a character vector.

Error in cell/setdiff (line 83)
    [varargout{1:nlhs}] = cellsetdiffR2012a(varargin{:});

Error in removeGitIgnoredNewFiles (line 23)
diffContent = setdiff(newContent, oldcontent);

Error in testAll (line 241)
removeGitIgnoredNewFiles(testDirPath,testDirContent);

When trying to follow this error, it turns out that testAll defines oldContent as the output of rdir (which returns "a structure with the same fields as Matlab DIR output"). 
removeGitIgnoredNewFiles line 19 uses system('git ls-files') to get the files and the git command returns a char array.
At that point, trying to compare a struct and a char gives an error.

It seems that removeGItIgnoredNewFIles will only work if testDirContent is defined as a char, perhaps by using 'system('ls')' or if removeGitIgnoredNewFIles will call rdir. I'm not sure what would be preferable.

**I hereby confirm that I have:**

- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [x] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

**Comment by rmtfleming** [comment]
Thanks a lot for this detailed investigation of an important issue.

**Comment by tpfau** [comment]
Thanks for the report.
The issue was/is, that this fail happened after the tests were run. on the CI testAll returns before this cleanup is called. 
There currently seems to be some issue with our Windows CI machines, but we are working on it and this should be fixed in the develop branch soon.

**Comment by tpfau** [comment]
Ok, bug on the Windows CI machines was caused due to some text being in a file which should not be there... My bad.

**Comment by tpfau** [comment]
This should be fixed with #1138

**Comment by laurentheirendt** [comment]
Thanks!
