### ISSUE TITLE
rdir is defined twice

### ISSUE THREAD

**Issue by akaviaLab** [opencobra/cobratoolbox#1131]
rdir is defined in 

cobratoolbox/external/rdir/rdir.m
AND
MATLAB.devTools/external/rdir/rdir.m

The main difference seems to be that the cobratoolbox one is newer, and filters out git files, which the MATLAB.devTools toolbox doesn't. This may explain issue #1130, but they both seem to return a struct.

enhanced_rdir.m is also present twice, but is identical file, so it doesn't matter.

**I hereby confirm that I have:**

- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

**Comment by laurentheirendt** [comment]
@akaviaLab, thank you for reporting this. We will fix that.

**Comment by laurentheirendt** [comment]
Thanks @akaviaLab. 

[related PR](https://github.com/opencobra/MATLAB.devTools/pull/13)
