### ISSUE TITLE
Create a rxnGenMat field when loading the model

### ISSUE THREAD

**Issue by feiranl** [opencobra/cobratoolbox#1149]
*Please include a short description of problem here*
When we do the essential gene analysis, we meet the followed errors, is that okay to add the field 'rxnGeneMat' when loading the model?
 
errors we met:
grRatio = singleGeneDeletion(model)
Single gene deletion analysis in progress ...
0% [ ]Reference to non-existent field 'rxnGeneMat'.
Error in deleteModelGenes (line 71)
rxnInd = find(any(model.rxnGeneMat(:,geneInd),2));

Error in singleGeneDeletion (line 130)
[modelDel,hasEffect(i),constrRxnNames] =
deleteModelGenes(model,geneList{i});

**I hereby confirm that I have:**

- [x] Tried to solve the issue on my own
- [x] Retried to run my code with the latest version of The COBRA Toolbox
- [x] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

**Comment by tpfau** [comment]
Personally, I would rather not build the field during load. 
But what you report definitely is a bug.
I've put in a PR that should fix this issue #1150

**Comment by laurentheirendt** [comment]
Thanks @feiranl for reporting and @tpfau for fixing.

@feiranl, contributions are welcome 🎉  

Please don't hesitate to [submit your pull request](https://opencobra.github.io/cobratoolbox/stable/contributing.html). 👍
