### ISSUE TITLE
convertToIrreversible() bug

### ISSUE THREAD

**Issue by WegrzynAB** [opencobra/cobratoolbox#115]
When I wanted to sample my model I needed to first make it irreversible. However after applying convertToIrreversible function (which worked OK) I couldn't use the obtained model_Irrev for the sampleCbModel.m as it didn't have the grRules field in it. I updated the convertToIrreversible.m function to added that field to the newly created model.

```
% Build final structure
modelIrrev.S = modelIrrev.S(:,1:cnt);
modelIrrev.ub = columnVector(modelIrrev.ub(1:cnt));
modelIrrev.lb = columnVector(modelIrrev.lb(1:cnt));
modelIrrev.c = columnVector(modelIrrev.c(1:cnt));
modelIrrev.rev = modelIrrev.rev(1:cnt);
modelIrrev.rev = columnVector(modelIrrev.rev == 1);
modelIrrev.rxns = columnVector(modelIrrev.rxns); 
modelIrrev.mets = model.mets;
matchRev = columnVector(matchRev(1:cnt));
modelIrrev.match = matchRev;
if (isfield(model,'b'))
    modelIrrev.b = model.b;
end
if isfield(model,'description')
    modelIrrev.description = [model.description ' irreversible'];
end
if isfield(model,'subSystems')
    modelIrrev.subSystems = model.subSystems(irrev2rev);
end
if isfield(model,'genes')
    modelIrrev.genes = model.genes;
    genemtxtranspose = model.rxnGeneMat';
    modelIrrev.rxnGeneMat = genemtxtranspose(:,irrev2rev)';
    modelIrrev.rules = model.rules(irrev2rev);
    modelIrrev.grRules = model.grRules(irrev2rev); %added to allow model reduction 18/02/2016 AW
end
```

**Comment by rmtfleming** [comment]
Please make a pull request with these suggested changes:
https://help.github.com/articles/creating-a-pull-request/

On 18 February 2016 at 19:26, WegrzynAB <notifications@github.com> wrote:

> When I wanted to sample my model I needed to first make it irreversible.
> However after applying convertToIrreversible function (which worked OK) I
> couldn't use the obtained model_Irrev for the sampleCbModel.m as it didn't
> have the grRules field in it. I updated the convertToIrreversible.m
> function to added that field to the newly created model.
>
> % Build final structure
> modelIrrev.S = modelIrrev.S(:,1:cnt);
> modelIrrev.ub = columnVector(modelIrrev.ub(1:cnt));
> modelIrrev.lb = columnVector(modelIrrev.lb(1:cnt));
> modelIrrev.c = columnVector(modelIrrev.c(1:cnt));
> modelIrrev.rev = modelIrrev.rev(1:cnt);
> modelIrrev.rev = columnVector(modelIrrev.rev == 1);
> modelIrrev.rxns = columnVector(modelIrrev.rxns);
> modelIrrev.mets = model.mets;
> matchRev = columnVector(matchRev(1:cnt));
> modelIrrev.match = matchRev;
> if (isfield(model,'b'))
>     modelIrrev.b = model.b;
> end
> if isfield(model,'description')
>     modelIrrev.description = [model.description ' irreversible'];
> end
> if isfield(model,'subSystems')
>     modelIrrev.subSystems = model.subSystems(irrev2rev);
> end
> if isfield(model,'genes')
>     modelIrrev.genes = model.genes;
>     genemtxtranspose = model.rxnGeneMat';
>     modelIrrev.rxnGeneMat = genemtxtranspose(:,irrev2rev)';
>     modelIrrev.rules = model.rules(irrev2rev);
>     modelIrrev.grRules = model.grRules(irrev2rev); %added to allow model reduction 18/02/2016 AW
> end
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencobra/cobratoolbox/issues/115>.
>



-- 
--
Mr. Ronan MT Fleming B.V.M.S. Dip. Math. Ph.D.
----------------------------------------------------------------------------
Senior research associate (EN) == Chercheur (FR),
Principal investigator,
Systems Biochemistry Group,
wwwen.uni.lu/lcsb/research/systems_biochemistry
Luxembourg Centre for Systems Biomedicine,
University of Luxembourg,
Campus Belval,
6, avenue du Swing,
L-4367 Belvaux.
&
National Centre of Excellence in Research on Parkinson’s disease
www.parkinson.lu
&
Adjunct Assistant Professor,
Division of Analytical Biosciences,
Leiden Academic Centre for Drug Research,
Faculty of Science,
University of Leiden.
http://analyticalbiosciences.leidenuniv.nl
----------------------------------------------------------------------------
Mobile:  +352 621 175 112
Office: +352 466 644 5528
Skype: ronan.fleming
----------------------------------------------------------------------------
(This message is confidential and may contain privileged information. It is
intended for the named recipient only. If you receive it in error please
notify me and permanently delete the original message and any copies.)
