### ISSUE TITLE
MOMA

### ISSUE THREAD

**Issue by hscotthinton** [opencobra/cobratoolbox#118]
MOMA does not work with the new gurobi (gurobi6). Below is the error lists

Error using solveCobraQP (line 422)
Unknown solver: gurobi6

Error in MOMA (line 209)
    QPsolution = solveCobraQP(QPproblem, 'printLevel', verbFlag-1);

Error in EthanolProduction_GDLS_Mutants_MOMA (line 21)
[solutionDel,solutionWT,totalFluxDiff,solStatus] =
MOMA(modelWT,modelMutant,'max','false')

**Comment by AndrasHartmann** [comment]
As far as I remember it is the same if you set the solver to gurobi5, it will call the gurobi function, just check if the gurobi function is correct (e.g. 'which gurobi' points to your gurobi 6)

**Comment by hscotthinton** [comment]
Thanks. If I change the solver to gurobi5 I get the following error

SWITCH expression must be a scalar or string constant.

Error in solveCobraQP (line 367)
        switch printLevel

Error in MOMA (line 209)
    QPsolution = solveCobraQP(QPproblem, 'printLevel', verbFlag-1);

Error in EthanolProduction_GDLS_Mutants_MOMA (line 21)
[solutionDel,solutionWT,totalFluxDiff,solStatus] =
MOMA(modelWT,modelMutant,'max','false')

Thanks for your help.

**Comment by mlehoai** [comment]
Dear Scott,
There is an error when you use the function MOMA. The last input should be **false** but not **'false'**. The line 21 of EthanolProduction_GDLS_Mutants_MOMA should be
MOMA(modelWT,modelMutant,'max',false) 
Regards,

Minh Le

**Comment by hscotthinton** [comment]
Minh,
Well that was embarrassing! Thanks so much!
                Scott
