### ISSUE TITLE
Incorrect multiplier for time units in SBML export

### ISSUE THREAD

**Issue by draeger** [opencobra/cobratoolbox#119]
The unit "millimole per gram dry weight per hour" mmol/gDW/h = 10<sup>-3</sup> mol &sdot; (gDW)<sup>-1</sup> &sdot; (3600 s)<sup>-1</sup> uses an incorrect multiplier. Instead of 3600 seconds per hour, it produces the multiplier 0.000277777777777778:

``` xml
<unitDefinition id="mmol_per_gDW_per_hr">
  <listOfUnits>
    <unit kind="mole" exponent="1" scale="-3" multiplier="1" offset="0"/>
    <unit kind="gram" exponent="-1" scale="0" multiplier="1" offset="0"/>
    <unit kind="second" exponent="-1" scale="0" multiplier="0.000277777777777778" offset="0"/>
  </listOfUnits>
</unitDefinition>
```

The reason is that instead of multiplying the numbers of minutes and seconds they are are divided, see
https://github.com/opencobra/cobratoolbox/blob/bb7176847770894a03669792177307e4804fb1a4/io/convertCobraToSBML.m#L95

**Comment by laurentheirendt** [comment]
@draeger, you seem to have a good idea on how to solve this issue. Could you please open a pull-request (PR) with the suggested changes in the code?

Guidelines on how to contribute are [here](https://github.com/opencobra/cobratoolbox/blob/master/.github/CONTRIBUTING.md).

Please let me know if you are running into any issues.

**Comment by draeger** [comment]
I think, @longfeimao had already solved this. Also, I don't know where exactly this line of code is located now as it seems there was a lot of refactoring since I originally posted this. It is only one wrong value and shouldn't be hard to change though.

**Comment by marouenbg** [comment]
Indeed, In line 154 of 
https://github.com/opencobra/cobratoolbox/blob/a5a02b9a82b266bb10461f9316b72e49c6f43581/src/io/utilities/writeSBML.m

Issue can be closed.

**Comment by laurentheirendt** [comment]
Thanks @marouenbg . What about the `unit_multipliers` in https://github.com/opencobra/cobratoolbox/blob/master/src/io/utilities/cobra_struct_to_sbml_struct.m#L84?

**Comment by marouenbg** [comment]
yeah, they are correct!

**Comment by laurentheirendt** [comment]
Thanks @marouenbg .
