### ISSUE TITLE
upload a metabolic model in excel format into Matlab CobraToolbox

### ISSUE THREAD

**Issue by ar00** [opencobra/cobratoolbox#1195]
*I formatted the fields in the two excel sheets of a single file bìnamed "Reaction List" and "Metabolite List" respectively according to the specifications provide in the example file. However I do not know which COBRA function is used to correctly read the file.*

**I hereby confirm that I have:**

- I tried to use the function xlsread() but only some numerical columns of the Reaction List are imported.
- I tried to use the function xls2model() by passing the two excel files separately model = xls2model('Rxns.xls','Mets.xls');

However I got the error: 
Excel is installed.
Error using fprintf
Invalid file identifier.  Use fopen to generate a valid file identifier.
Error in xls2model (line 102)
        fprintf(strrep(sheets, '\', '\\'));

- I checked that a similar issue has not already been opened

**Comment by laurentheirendt** [comment]
Did you try `readCbModel()`? There is a tutorial that might help: https://opencobra.github.io/cobratoolbox/stable/tutorials/tutorialIO.html

For this type of support, I recommend posting in the [forum](https://groups.google.com/forum/#!forum/cobra-toolbox).

**Comment by ar00** [comment]
Dear All,

I followed your suggestions and posted the request on the forum.

I repeatedly tried any possible format I could. I would be thankful if you
might provide me with some suggestions.

Angela Re


2018-05-09 10:54 GMT+02:00 Laurent Heirendt <notifications@github.com>:

**Comment by laurentheirendt** [comment]
Sounds good 👍 

Closing here now.
