### ISSUE TITLE
Recent createMultipleSpeciesModel doesn't adjust csense

### ISSUE THREAD

**Issue by bbarker** [opencobra/cobratoolbox#1227]
`model.csense` should have length equal to `model.rxns`; currently `createMultipleSpeciesModel` seems to not touch the value, so the output multispecies model still has length equal to the old # of reactions.

```
msModel =  createMultipleSpeciesModel({iAF1260}, {'modelIn'});

>> optimizeCbModel(msModel)
Error using optimizeCbModel (line 304)
The length of csense does not match the number of rows of model.S.

```

Possible workaround that seems to fix the issue:

```
>> msModel.csense = repmat(['E'], 1, length(msModel.mets));
>> optimizeCbModel(msModel);
```
**I hereby confirm that I have:**

- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
Using the latest version from master - I don't believe this was a problem a few months ago, but haven't tested older releases.
- [X] Checked that a similar issue has not already been opened

**Comment by tpfau** [comment]
This should be fixed now.

**Comment by laurentheirendt** [comment]
Thanks @bbarker and @tpfau 👍
