### ISSUE TITLE
In sequential mode, fvamin and fvamax are always zeros in fastFVA

### ISSUE THREAD

**Issue by akaviaLab** [opencobra/cobratoolbox#1267]
Lines 618-619 in fastFVA.m set fvamin and fvamax as all zeros
    fvamin = zeros(length(model.rxns), length(model.rxns));
    fvamax = zeros(length(model.rxns), length(model.rxns));

But the values are filled in only if number of workers is above 1. Therefore, when running on sequential mode, it will always be zero.

I'm not 100% sure how this is supposed to be fixed. I think that some variant of lines 636-637
        fvamin(:, indices) = fvaminRes{i};
        fvamax(:, indices) = fvamaxRes{i};

Should be moved outside the loop 628-645 "for i=1:nworkers"

**I hereby confirm that I have:**

- [ ] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

**Comment by laurentheirendt** [comment]
@akaviaLab, thanks for spotting this! I submitted a PR and added a test.
