### ISSUE TITLE
LPproblem.A not defiend in optimizeCbModel()

### ISSUE THREAD

**Issue by djomangan** [opencobra/cobratoolbox#128]
`LPproblem.A` is defined after it is used in optimizeCbModel.m file

`% Fill in the RHS vector if not provided
if ~isfield(model,'b')
    warning('LP problem has no defined b in S*v=b. b should be defined, for now we assume b=0')
    LPproblem.b=zeros(size(LPproblem.A,1),1);
else
    LPproblem.b = model.b;
end

% Rest of the LP problem
[m,n] = size(model.S);
LPproblem.A = model.S;
LPproblem.c = model.c;
LPproblem.lb = model.lb;
LPproblem.ub = model.ub;`

**Comment by mlehoai** [comment]
Dear djomangan,

We have fixed the error. 
Thank you for reporting this issue.

Regards,
Minh Le
