### ISSUE TITLE
test13CFitting is not working

### ISSUE THREAD

**Issue by djomangan** [opencobra/cobratoolbox#129]
test13CFitting is not working.
I have experiences several bugs with solveCobraNLP when trying to use matlab NLP solver

changeCobraSolver('matlab','NLP');

When looking deeply in the code, it seems that several variables are not defined before they are use.

Hope that you will fix the problem

Best,
Adama.

**Error code**
`Undefined function or variable 'csense'.

Error in solveCobraNLP (line 148)
        A1 = [A(csense == 'L',:);-A(csense ==
        'G',:)];

Error in fitC13Data (line 76)
    NLPsolution = solveCobraNLP(NLPproblem,
    'checkNaN', cnan, 'printLevel', printLevel,
    'iterationLimit', majorIterationLimit,
    'logFile', 'minimize_SNOPT.txt');

Error in testC13Fitting (line 38)
[vout, rout] = fitC13Data(v0,expdata,model,
majorIterationLimit);`

**Comment by laurentheirendt** [comment]
Closing as fixed by PR #335.
