### ISSUE TITLE
issue with xls2model

### ISSUE THREAD

**Issue by Sunweikang** [opencobra/cobratoolbox#1315]
*Please include a short description of problem here*
hello 
when I am using the xls2model to convert the excel sheet to S model, in the end of the reading the reaction list, problem  occurred:
cannot be converted to logicals.

Error in createModel (line 111)
    model = addReaction(model,{rxnAbrList{i},rxnNameList{i}},metaboliteList,stoichCoeffList,...
Error in xls2model (line 132)
model =
createModel(rxnAbrList,rxnNameList,rxnList,revFlagList,lowerBoundList,upperBoundList,subSystemList,grRuleList); 
<img width="499" alt="default" src="https://user-images.githubusercontent.com/40064136/44571424-590fea80-a7b3-11e8-9853-d726d83f9c43.PNG">

- [x] Tried to solve the issue on my own
- [x] Retried to run my code with the latest version of The COBRA Toolbox
- [x] Checked that a similar issue has not already been opened

*(Note: You may replace [ ] with [X] to check the box)*

**Comment by laurentheirendt** [comment]
May you share your input files?

**Comment by Sunweikang** [comment]
yes, thank you so much !
[roughmodel.xlsx](https://github.com/opencobra/cobratoolbox/files/2317488/roughmodel.xlsx)

**Comment by Sunweikang** [comment]
Can you fix it ?

**Comment by laurentheirendt** [comment]
Maybe this helps: https://opencobra.github.io/cobratoolbox/stable/tutorials/tutorialIO.html

Also, make sure to have all bounds specified.

**Comment by Sunweikang** [comment]
but the heads and other name and GPR type is right, I  have  already read that before , so I really donnot know the source of the problem.

**Comment by Sunweikang** [comment]
I have fix it by my own, thanks for your help anyway.

**Comment by laurentheirendt** [comment]
What was the issue?
