### ISSUE TITLE
empty folders when downloading as zip or cloning

### ISSUE THREAD

**Issue by arichelle** [opencobra/cobratoolbox#1329]
I had to reinstall the latest version of cobra on a new computer and figured that the following folders are empty regardless of the method used to obtain cobra (zip or clone):
cobratoolbox/binary
cobratoolbox/papers
cobratoolbox/tutorials
cobratoolbox/test/models

and maybe other that present the @ in their names

This obviously leads to the failure of the initialization of cobra as mentioned for example in the following post on the forum https://groups.google.com/forum/#!msg/cobra-toolbox/UKPDMPZfoP0/Df8EbpjyBAAJ

*Please include a short description of problem here*

**I hereby confirm that I have:**

- [ ] Tried to solve the issue on my own
- [ ] Retried to run my code with the latest version of The COBRA Toolbox
- [ ] Checked that a similar issue has not already been opened

*(Note: You may replace [ ] with [X] to check the box)*

**Comment by arichelle** [comment]
OK make sense! I try to install it on a windows :/ then it should be a problem with the git connection  and specifically
[status_gitSubmodule, result_gitSubmodule] = system(['git submodule update --init --remote --no-fetch ' depthFlag]);

when I call this function this is the response
status_gitSubmodule =
     1
result_gitSubmodule =
fatal: Needed a single revision
Unable to find current revision in submodule path 'papers'

Note that I had to setup a proxy server to connect internet doing so I already changed the remote call of line 713 initCobraToolbox from
[status_curl, result_curl] = system('curl -s -k --head https://github.com/opencobra/cobratoolbox');
to
[status_curl, result_curl] = system('curl -s -k --proxy http://<domain>\<user>:<password>@gskproxy.gsk.com:800 --head https://github.com/opencobra/cobratoolbox')

**Comment by laurentheirendt** [comment]
May you try cloning the COBRA Toolbox with:
```
$ git clone https://github.com/opencobra/cobratoolbox.git cobratoolbox
```
Then, open MATLAB, and run:
```
>> restoredefaultpath;
>> cd cobratoolbox
>> initCobraToolbox
```

**Comment by tpfau** [comment]
@arichelle What might also help is setting a global git proxy as explained e.g. [here](https://gist.github.com/evantoli/f8c23a37eb3558ab8765)

**Comment by arichelle** [comment]
Great it works ! Thank you @tpfau & @laurentheirendt

**Comment by tpfau** [comment]
@arichelle : What worked in the end? setting up the proxy? Or cloninig with https?
Would be interesting as we could put this in the troubleshooting section of the installation guide.

**Comment by arichelle** [comment]
I have reset the proxy as mentioned in your link, deleted my cobra folder and re-cloned it.
I also changed 2 lines in the initCorbaToolbox related to curl using the proxy
Change line 713 in initCobraToolbox.m
From
[status_curl, result_curl] = system('curl -s -k --head https://github.com/opencobra/cobratoolbox');
to
[status_curl, result_curl] = system('curl -s -k --proxy http://ServerDomain\UserName:Password@proxy.com:800 --head https://github.com/opencobra/cobratoolbox') 

Change line 716 in initCobraToolbox.m
from
if status_curl == 0 && ~isempty(strfind(result_curl, ' 200'))
to 
if status_curl == 0 && ~isempty(strfind(result_curl, 'HTTP/1.0 200 Connection established'))

**Comment by arichelle** [comment]
Just figures that the modif of line 716 is not necessary

**Comment by tpfau** [comment]
If you configured the proxy, is the setting in 713 still necessary?

**Comment by arichelle** [comment]
yes

**Comment by laurentheirendt** [comment]
Thanks @arichelle for reporting! Great to hear that the issue got solved.
