### ISSUE TITLE
How i should create a fit input for mgPipe?

### ISSUE THREAD

**Issue by PejmanS** [opencobra/cobratoolbox#1383]
*I couldn't adapt taxon names with AGORA*

**I hereby confirm that I have:**

- [x] Tried to solve the issue on my own
- [x] Retried to run my code with the latest version of The COBRA Toolbox

**Comment by tpfau** [comment]
@ithiele  @almut-heinken @Fede-edef 
You are probably the people who could help best here.

**Comment by PejmanS** [comment]
@tpfau Thanks Thomas!

@almut-heinken Thanks for your guidance.
Would you please suggest me some ways and databases that have data are more compatible with AGORA?
I'm using EBI MGnify and some taxon abundances are available just for Kingdom level! Is it related to pipeline version?

**Comment by laurentheirendt** [comment]
Thanks @PejmanS. You may find [our forum](https://groups.google.com/forum/#!tags/cobra-toolbox/toolbox) more useful for asking this kind of questions.
