### ISSUE TITLE
Bug in readSBML

### ISSUE THREAD

**Issue by alexandra-m-reimers** [opencobra/cobratoolbox#140]
There is a bug in line 544 of readSBML:
metTmp=[metTmp,'[',modelSBML.species(1).compartment,']'];

It should be species(i), not species(1). This bug has the effect that all metabolites end up in the same compartment, which is the compartment of the first metabolite in the model.

**Comment by akaviaLab** [comment]
This seems fixed in Github current version. Should it be closed?

**Comment by syarra** [comment]
@longfeimao, Please close this issue if you are satisfied with the fix you provided in 826ad29cda00ca718abbd22a76c4fad39b5568c8.
