### ISSUE TITLE
CHRR vs ACHR in cobratoolbox 

### ISSUE THREAD

**Issue by kspkritika** [opencobra/cobratoolbox#1422]
I am trying to use the sampling algorithm on cobratoolbox in MATLAB to get unbiased flux samples for EColi core model. However when I use the CHRR algorithm, the flux values for reactions corresponding to glucose uptake and biomass produced are very small (order of magnitude ~=10^-14). This does not make any sense physiologically. And when I use the ACHR algorithm, some reactions are eliminated in the final flux samples. Which defies the purpose of the problem I want to solve. I am new to cobratoolbox. Can someone guide me with a way to deal with this problem.

**Comment by laurentheirendt** [comment]
@kspkritika, eventually it might be best to raise this issue in our [forum](https://groups.google.com/forum/?nomobile=true#!forum/cobra-toolbox). Thanks 👍
