### ISSUE TITLE
Getting different errors using CHRR

### ISSUE THREAD

**Issue by shirinfa** [opencobra/cobratoolbox#1432]
Hi, 
I have tried to use sampleCbModel() to do sampling with CHRR method and I tried it on different models. It is working only for "e_coli_core" model on my computer. I have tried it for "iYO844" model and got Error :Input to SVD must not contain NaN or Inf. I tried for "iJR904" and got Error: using mve_solver_cobra (line 29), x0 not interior. I found that other people had the same problem I faced (https://github.com/Bounciness/Volume-and-Sampling/issues/4 , or  https://groups.google.com/forum/#!msg/cobra-toolbox/Y44uYQtGbpI/iJRg8pGbAwAJ). However none of those suggestions helped me to solve the problem. My computer is MacOS 10.14.3 and I am using Matlab2016b and Gurobi as optimizer. I have the latest version of Cobra toolbox  (2019). 
 
I really appreciate if you can guide me in this issue. I do not know what the problem is since I get different type of errors depending on the model I tried to sample from. 
**I hereby confirm that I have:**

- [X ] Tried to solve the issue on my own
- [ X] Retried to run my code with the latest version of The COBRA Toolbox
- [ ] Checked that a similar issue has not already been opened

*(Note: You may replace [ ] with [X] to check the box)*

**Comment by rmtfleming** [comment]
Please post this to the google group (with a more complete explanation of the exact error reported by matlab).
