### ISSUE TITLE
Reference to non-existent  'geneKO.matrix'.

### ISSUE THREAD

**Issue by Saiteja-Reddy** [opencobra/cobratoolbox#1436]
While using the MTA function, if the optional argument 'rxnKO' is set to true, the function returns an error saying:

`
Reference to non-existent field 'matrix'.
Error in MTA (line 108)
[geneKO.matrix,geneKO.IA,geneKO.IC ] = unique(geneKO.matrix','rows');
 `

The problem I have identified is that if rxnKO is set to true, `geneKO.matrix` is not defined anywhere. 
In the below lines of the code, geneKO.matrix is not set. I am guessing the problem might be with the line with speye function. 

`
% Calculate perturbation matrix
if rxnKO
    geneKO.genes = model.rxns;
    geneKO.rxns = model.rxns;
    geneKO.rxns = speye(numel(model.rxns));
`
[Code to Toolbox MTA function](https://github.com/opencobra/cobratoolbox/blob/master/src/analysis/rMTA/MTA.m#L97)

- [ ] Tried to solve the issue on my own
- [ ] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

*(Note: You may replace [ ] with [X] to check the box)*

**Comment by lvalcarcel** [comment]
Thanks for the comment.

I have already uploaded a solution for this issue a month ago in COBRA, but I have some issues with the test in Jenkins. Please, downlaod the new file from the pull request 
https://github.com/opencobra/cobratoolbox/pull/1424

**Comment by laurentheirendt** [comment]
Thanks @Saiteja-Reddy and @lvalcarcel 👍
