### ISSUE TITLE
Tomlab_cplex doesn't work in CT > 3.0.0

### ISSUE THREAD

**Issue by leejm516** [opencobra/cobratoolbox#1449]
*Please include a short description of problem here*

I recently found that tomlab_cplex doesn't work properly.
```
> changeCobraSolver('tomlab_cplex', 'lp')
Solver tomlab_cplex is installed but not working properly.
```

I checked whether my tomlab worked properly, and there was no problem on that.
Thus, I tried on my own to find what was the problem in the COBRA toolbox.
The codes really baffled me, but I managed to find some codes making troubles.

1. Line 1151, solveCobraLP.m:
`Result = cplexTL(tomlabProblem);`
This returns an error because xtol was not defined in the tomlabProblem.
This issue has solved when I replaced it with
`Result = tomRun('cplex', tomlabProblem)`

2. Line 498, solveCobraMILP.m:
`tomlabProblem = updateStruct(tomlabProblem.MIP.cpxControl,solverParams);`
`updateStruct` seems like a mistake of `updateStructData`, and it should be:
`tomlabProblem.cpxControl = updateStructData(tomlabProblem.MIP.cpxControl,solverParams);`

I have not looked at details of the other codes and solver parameters,
so what I suggest above may not be the best solution.

It would be nice if some of the developers debug this issue.

Thanks,
Joungmin

**I hereby confirm that I have:**

- [x] Tried to solve the issue on my own
- [x] Retried to run my code with the latest version of The COBRA Toolbox
- [x] Checked that a similar issue has not already been opened

**Comment by rmtfleming** [comment]
Fixed in upcoming PR
>> changeCobraSolver('tomlab_cplex', 'lp')

 > changeCobraSolver: Tomlab interface added to MATLAB path.
 > isCompatible: tomlab_cplex (version 86) is compatible and fully tested with MATLAB R2019a on your operating system.

ans =

  logical

   1

>> version

ans =

    '9.6.0.1214997 (R2019a) Update 6'
