### ISSUE TITLE
addMultipleMetabolites error

### ISSUE THREAD

**Issue by jep38** [opencobra/cobratoolbox#1463]
When running addMulitpleMetabolites with either my own input or with the example from the m file, a series of errors are returned: 

My version of the example from the m file:
example = addMultipleMetabolites(test,{'A','b','c'},'metCharges', [ -1 1 0], 'metFormulas', {'C','CO2','H2OKOPF'}, 'metKEGGID',{'C000012','C000023','C000055'})

test = a Cb model that has passed the verifyModel: simpleCheck

Errors:
> Error using extendIndicesInDimenion (line 28)
> Right hand side of an assignment into a table must be another table or a cell array.
> 
> Error in extendModelFieldsForType (line 139)
>             model.(cfield) = extendIndicesInDimenion(model.(cfield),cdim,defaultValue, targetSize-originalSize);
> 
> Error in addMultipleMetabolites (line 106)
> newmodel = extendModelFieldsForType(model,'mets','originalSize',nMets);

**I hereby confirm that I have:**

- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

*(Note: You may replace [ ] with [X] to check the box)*

**Comment by tpfau** [comment]
Thats odd.
Could you provide the model you used?

**Comment by jep38** [comment]
Thanks for the quick follow up.

The context for this model and the main thrust of the work is to compare alternate genome annotations from my favorite bacteria along with some omics data to develop a consensus reconstruction from which I can infer a metabolic network in which anaerobic respiration is feasible.

The underlying SBML data is from Pathway Tools.

Thanks, J
[test.zip](https://github.com/opencobra/cobratoolbox/files/3116469/test.zip)

**Comment by jep38** [comment]
Troubleshooting further, it seems like the problem arises at readSBML

Here's my script that reads SBML [.xml] files exported from Pathway Tools and immediately checks the format of the mets field to generate the error following:

`for k = 1 %: numel(SBML_Names)
    SBML_Struct = readSBML(SBML_Full_Names{k},defaultBound);
    SBML_Struct.verify_model.verify_requiredFields.mets = verifyModel(SBML_Struct,'requiredFields',true,{'mets'});
…
end`

The error is:
`Error using verifyModel (line 73)
The value of 'requiredFields' is invalid. It must satisfy the function: @(x)iscell(x)&&all(cellfun(@ischar,x)).`

It isn't obvious where the state violation occurs -- at least to me.

[MavExpt.zip](https://github.com/opencobra/cobratoolbox/files/3116590/MavExpt.zip)

**Comment by tpfau** [comment]
The Model you provide has a type of field, that is currently not anticipated/supported, namely a table (the field `metNotes_parsed`). 
This is currently not supported, as we don't have any defined table fields, and were not expecting this to happen. It could take some time to get a fix for this so for the moment I would suggest to remove the field for modifications and manually add it later.

**Comment by jep38** [comment]
tpfau, thanks for looking into this -- yes, the tables are the product of a parsing script that I wrote to overcome the opacity of the underlying SBML data.

Since the compound and reaction data that comes out of Pathway Tools is non-human readable [for example BioCyc CPD-0923 refers to a specific chemical entity], I want to use BiGG-style met ids. My parsing script extracts the contents of metNotes and rxnNotes into tables so they can be translated using universal BiGG and BioCyc data sets to get inchis and thus build non-ambiguous mass- and charge-balanced reactions. This is important because Pathway Tools uses placeholder 'classes' of compounds to instantiate an unknown reaction during its Pathway Hole Filling -- it's SBML contains these placeholder and inherently ambiguous compounds and reactions.

I'll try to replicate the error in a strict cobra structure and let you know. Thanks, John

**Comment by tpfau** [comment]
I've written a fix that should allow the use of table fields #1465, and thus the model you currently have.
The biggest issue with tables is that defaults are difficult to set (I'm now using NaN for numeric values (or 0 for those numeric types which don't have NaN), false for logical and empty strings for textual data. But if the table contains non native types than we can't handle it.

**Comment by jep38** [comment]
tpfau, thank you!

**Comment by laurentheirendt** [comment]
Thanks @tpfau and @jep38 👍
