### ISSUE TITLE
what is DM_coumpound ID after running [missingMets,presentMets] = biomassPrecursorCheck(model)

### ISSUE THREAD

**Issue by dipesh100** [opencobra/cobratoolbox#147]
example - 
DM_C00459[c]            C00459[c]   ->  
DM_C00458[c]    C00458[c]   ->  
DM_C00286[c]    C00286[c]   ->

**Comment by tpfau** [comment]
DM_ reactions are commonly demand reactions. (Does this answer your question?)

**Comment by syarra** [comment]
@dipesh100, does this anwer your question?

**Comment by syarra** [comment]
Thank you @tpfau!
Closing this issue!
