### ISSUE TITLE
Error in creating Pan models

### ISSUE THREAD

**Issue by PejmanS** [opencobra/cobratoolbox#1491]
in createPanModels function what is problem?

ans = 

   Empty cell array: 0-by-1

Warning: Variable names were modified to make them valid MATLAB identifiers. 
Index exceeds matrix dimensions.

Error in createPanModels (line 203)
dietConstraints(:, 2) = cellstr(num2str(cell2mat(dietConstraints(:, 2))));

- [x] Tried to solve the issue on my own
- [x] Retried to run my code with the latest version of The COBRA Toolbox
- [x] Checked that a similar issue has not already been opened

**Comment by almut-heinken** [comment]
Hello @PejmanS,
I am not getting the same error. May you tell the output you get for
which 'WesternDietAGORA.txt'
Thanks,
Almut

**Comment by PejmanS** [comment]
I chenged my machine and it worked. But there is a new error:

Warning: Unable to determine the format of the DATETIME data.
Try adding a format to the DATETIME specifier. e.g. '%{MM/dd/uuuu}D'. 
> In table/readTextFile>textscanReadData (line 532)
  In table/readTextFile (line 205)
  In table.readFromFile (line 39)
  In readtable (line 198)
  In createPanModels (line 37)

**Comment by almut-heinken** [comment]
Hello @PejmanS ,
this is a warning, not an error, and I don't think it affects the function. I think you can ignore it.
Best,
Almut

**Comment by PejmanS** [comment]
Unfortunately it doesn't create models!

**Comment by almut-heinken** [comment]
I cannot reproduce that either. What code did you use to run the function?

**Comment by PejmanS** [comment]
createPanModels('i:\microbiome\AGORA\', 'i:\microbiome\AGORApan\', 'species')

**Comment by almut-heinken** [comment]
'species' needs to be 'Species' with capital S. Are the mat files of the AGORA reconstructions located in 'i:\microbiome\AGORA'? Then it should work.

**Comment by PejmanS** [comment]
Thanks, it worked.
