### ISSUE TITLE
How to prevent creation of log files?

### ISSUE THREAD

**Issue by almut-heinken** [opencobra/cobratoolbox#1493]
Hello,
when I solve a LP problem, several log files are created each time (CobraLPSolver.LP, clone1.log, clone2.log). Is there a way to prevent these files from being created?
Thanks in advance,
Almut

**I hereby confirm that I have:**

- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

*(Note: You may replace [ ] with [X] to check the box)*

**Comment by tpfau** [comment]
clone1.log and clone2.log are created by CPLEX. you could have a look at the CPLEX docu and see if there is a way not to create them at all. You can pass that to solveCobraLP using the params struct.
As for the CobraLPSolver.LP:
This should be deactivated if you call `changeCobraSolverParams('LP', 'logFile', 0)

**Comment by almut-heinken** [comment]
Hi @tpfau,
thanks for the answer! When I run changeCobraSolverParams('LP', 'logFile', 0);,
the CobraSolver log file indeed disappears, but instead a get this output in the Command Window:

CPXPARAM_Simplex_Tolerances_Feasibility          1.0000000000000001e-09
CPXPARAM_Simplex_Display                         0
CPXPARAM_Sifting_Display                         0
CPXPARAM_Output_CloneLog                         1
CPXPARAM_Barrier_ConvergeTol                     1.0000000000000001e-09
CPXPARAM_Barrier_Display                         0
CPXPARAM_Network_Tolerances_Feasibility          1.0000000000000001e-09

Is that supposed to happen? 
I also think that cobraParams.logFile should already be passed on to setCplexParametersForProblem, so CPXPARAM_Output_CloneLog should also be set to 0 if cobraParams.logFile is 0
(https://github.com/opencobra/cobratoolbox/blob/2ed83d14eb0e7877856c34ae10f192013b8cdffe/src/base/solvers/setCplexParametersForProblem.m). I am not entirely sure though.
Best,
Almut

**Comment by tpfau** [comment]
I submitted a pull request that allows you to remove the clone.log files as well and properly handles a priintLevel of 0 (which wasn't done yet).
Once thats in, you should be able to disable logging entirely by either setting an empty logFile  or a logFile of 0 (via `setCobraSlverParams`). 
The display issue will also be solved, since this now depends on the printlevel. i.e. if the printLevel parameter is set to 0, the Cplex display function will be set to [] (i.e. no display).

**Comment by laurentheirendt** [comment]
Fixed in #1494. Thanks @tpfau.
