### ISSUE TITLE
Transport response is not recognized

### ISSUE THREAD

**Issue by lemoncxd** [opencobra/cobratoolbox#1497]
*Please include a short description of problem here*
There is a transport reaction in the model, but the transport response is 0 after using the [transRxns,nonTransRxns] = findTransRxns(model,true).
**I hereby confirm that I have:**

- [x] Tried to solve the issue on my own
- [ ] Retried to run my code with the latest version of The COBRA Toolbox
- [x] Checked that a similar issue has not already been opened

*(Note: You may replace [ ] with [X] to check the box)*

**Comment by tpfau** [comment]
Which model are you using? 
Could you attach the model and the name of the reaction that is incorrectly classified?

**Comment by lemoncxd** [comment]
I am a model built with Carve，the model version built is level="3" version="1". No error was reported after using the command, but the number of transport responses is 0. Is it because the version does not apply?



------------------ 原始邮件 ------------------
发件人: "Thomas Pfau"; 
发送时间: 2019年8月6日(星期二) 晚上6:35
收件人: "opencobra/cobratoolbox";
抄送: "lemoncxd"<367290017@qq.com>;"Author";
主题: Re: [opencobra/cobratoolbox] Transport response is not recognized(#1497)




Which model are you using?
 Could you attach the model and the name of the reaction that is incorrectly classified?
 
&mdash;

**Comment by tpfau** [comment]
It seems you have an sbml model. Could you attach the model file?

**Comment by lemoncxd** [comment]
This model is smbl format, converted to mat format when matlab




------------------ 原始邮件 ------------------
发件人: "Thomas Pfau"<notifications@github.com>;
发送时间: 2019年8月6日(星期二) 晚上10:42
收件人: "opencobra/cobratoolbox"<cobratoolbox@noreply.github.com>;
抄送: "竹七"<367290017@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [opencobra/cobratoolbox] Transport response is not recognized(#1497)




It seems you have an sbml model. Could you attach the model file?

**Comment by tpfau** [comment]
Still, without the model file it is hard to say if something is wrong with the model, or if there is an error in the toolbox. Could you attach the model so that we can address your issue properly please.

**Comment by lemoncxd** [comment]
Hello, the model is in the attachment, please look at you


------------------ 原始邮件 ------------------
发件人: "Thomas Pfau"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 凌晨2:24
收件人: "opencobra/cobratoolbox"<cobratoolbox@noreply.github.com>;
抄送: "竹七"<367290017@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [opencobra/cobratoolbox] Transport response is not recognized(#1497)




Still, without the model file it is hard to say if something is wrong with the model, or if there is an error in the toolbox. Could you attach the model so that we can address your issue properly please.

**Comment by tpfau** [comment]
Unfortunately, if you just respond to the email, the file wont be attached to the github message. Could you go directly to the issue and upload the file (just drag it into the message text box).

Thank you

**Comment by lemoncxd** [comment]
[PSU_1.zip](https://github.com/opencobra/cobratoolbox/files/3485398/PSU_1.zip)
Thank you, can you see the model now?

**Comment by tpfau** [comment]
I'm not sure how this model was converted to a cobra model from SBML, but I'm pretty sure it was not loaded via `readCbModel`.
The model you provide does not adhere to the nomenclature standard for compartments used in the COBRA Toolbox. The way the Toolbox identifies metabolite compartments is by having the compartment abbreviation in brackets behind the metabolite id (e.g. `metID[x]`). What you have there is the BiGG nomenclature, which unfortunately does not fit to the COBRA Toolbox.
We are currently working on this, but for now, you will have to replace the compartment identifiers to a COBRA Toolbox compliant style.

**Comment by lemoncxd** [comment]
Thank you very much for your help, I will try to modify the format of the model.

**Comment by laurentheirendt** [comment]
Closing for now - please reopen if necessary.
