### ISSUE TITLE
error in initializing submodules

### ISSUE THREAD

**Issue by almut-heinken** [opencobra/cobratoolbox#1509]
Hello,
since my last update of my repository, I am getting the following error when running initCobraToolbox:

> Initializing and updating submodules (this may take a while)...Cloning into 'C:/Users/Almut Heinken/Documents/GitHub/cobratoolbox/external/base/samplers/constrained-logconcave-sampler'...
remote: Repository not found.
fatal: repository 'https://github.com/Bounciness/constrained-logconcave-sampler/' not found
fatal: clone of 'https://github.com/Bounciness/constrained-logconcave-sampler' into submodule path 'C:/Users/Almut Heinken/Documents/GitHub/cobratoolbox/external/base/samplers/constrained-logconcave-sampler' failed
Failed to clone 'external/base/samplers/constrained-logconcave-sampler'. Retry scheduled
Cloning into 'C:/Users/Almut Heinken/Documents/GitHub/cobratoolbox/external/base/samplers/constrained-logconcave-sampler'...
remote: Repository not found.
fatal: repository 'https://github.com/Bounciness/constrained-logconcave-sampler/' not found
fatal: clone of 'https://github.com/Bounciness/constrained-logconcave-sampler' into submodule path 'C:/Users/Almut Heinken/Documents/GitHub/cobratoolbox/external/base/samplers/constrained-logconcave-sampler' failed
Failed to clone 'external/base/samplers/constrained-logconcave-sampler' a second time, aborting
Error using initCobraToolbox (line 205)
The submodules could not be initialized.

I get the same problem when I try to update the submodules in GitHub.
I appreciate any help.
Thank you in advance,
Almut

**I hereby confirm that I have:**

- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

*(Note: You may replace [ ] with [X] to check the box)*

**Comment by almut-heinken** [comment]
It seems it is trying to clone from a repository that doesn't exist, any ideas?

**Comment by BioLCD** [comment]
Hi,

I noticed that you previously addressed an issue related to executing the CobraToolbox command "initCobraToolbox()", and I was hoping you might be able to assist with an error I’m encountering.

When attempting to run the command in MATLAB, I encounter the following:

"> Initialising and updating submodules (this may take a while)...  
Error using initCobraToolbox (line 245)  
Failed to retrieve submodule paths."

To clone the repository, I used the following git commands:

"git clone https://github.com/opencobra/cobratoolbox.git cobratoolbox  
git submodule update --init --recursive"

Despite this, the error persists.

I also attempted to manually download the submodules by using the commands:

"git clone https://github.com/sbmlteam/libsbml.git external/libSBML  
git clone https://github.com/opencobra/gurobimop.git external/gurobimop"

Unfortunately, this did not resolve the issue.

I would greatly appreciate any guidance or suggestions you may have on resolving this.

Many thanks in advance for your help.

Best regards, Luis

![Image](https://github.com/user-attachments/assets/ce336ccd-1532-4e9b-ae04-aca2c34c7528)
