### ISSUE TITLE
gurobi seems not to be working on macOS

### ISSUE THREAD

**Issue by rmtfleming** [opencobra/cobratoolbox#1521]
https://prince.lcsb.uni.lu/jenkins/job/COBRAToolbox-pr-auto-macOS/MATLAB_VER=R2018b,label=lcsbs-mac-pro/1493/consoleFull

testQFCA.m is only reliably compatible with gurobi and needs to be bypassed if gurobi is not present

**Comment by laurentheirendt** [comment]
This is fixed now.
