### ISSUE TITLE
Error using minNorm

### ISSUE THREAD

**Issue by almut-heinken** [opencobra/cobratoolbox#1524]
Dear all,
when I try to use optimizeCbModel while minimizing the squared Euclidean Norm of internal fluxes, I get the following error with every model I tried including the E. coli core model.

initCobraToolbox
load('ecoli_core_model.mat')
solution=optimizeCbModel(model, 'max', '1e-6');
Error using spdiags (line 95)
For the syntax spdiags(B,d,m,n), the size of B must be min(m,n)-by-length(d).

Error in optimizeCbModel (line 355)
    LPproblem.F = spdiags(minNorm,0,nRxns,nRxns);

May you have a look into what is going on?
Thanks in advance!

**I hereby confirm that I have:**

- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

*(Note: You may replace [ ] with [X] to check the box)*

**Comment by rmtfleming** [comment]
The call is 
solution=optimizeCbModel(model, 'max', 1e-6);
rather than
solution=optimizeCbModel(model, 'max', '1e-6');

**Comment by almut-heinken** [comment]
Whoops, sorry.
