### ISSUE TITLE
Possible Regression Bug in preprocess.m

### ISSUE THREAD

**Issue by qacwnfq** [opencobra/cobratoolbox#1542]
In previous versions of the cobratoolbox I could sample the e_coli_core network using the master-branch of the cobratoolbox.
The model correctly had 23 dimensions after separating out the degenerate dimensions.

After grabbing the latest commit in all submodules and on the master branch however, the
cobratoolbox finds too many degenerate equations and the e_coli_core model is left with just 2 non-degenerate dimensions.

I can fix my Problem by using an older version of the repository I had on a different computer,
I just thought I'd let you know.

**I hereby confirm that I have:**

- [x] Tried to solve the issue on my own
- [x] Retried to run my code with the latest version of The COBRA Toolbox
- [x] Checked that a similar issue has not already been opened

**Comment by rmtfleming** [comment]
Thanks for identifying this. Please can you make a pr with the improvement?
https://opencobra.github.io/cobratoolbox/stable/contributing.html

**Comment by qacwnfq** [comment]
Unfortunately I don't know what exactly went wrong in the last few commits and I can not promise to fix it in a timely manner.
I only know that it works correct with commit c67a68b9e160d9da7ed97caa5026bf35a5ca3aa5.

**Comment by qacwnfq** [comment]
Works again, thanks!
