### ISSUE TITLE
Hardcoded reaction constraint in optimizeCbModel can cause unexpected FBA behavior

### ISSUE THREAD

**Issue by bheavner** [opencobra/cobratoolbox#16]
Line 242 of optimizeCbModel is currently

LPproblem2.ub = [model.ub;10000_ones(2_nRxns,1)];

This hard coding of a max upper bound of 10000 for unconstrained reactions can lead to infeasible solutions or other unexpected behavior for simulations that have large (but not unconstrained) upper limits.

When using gurobi 5.60, such behavior can be fixed by relaxing this upper bound by changing line 242 to:

LPproblem2.ub = [model.ub;inf_ones(2_nRxns,1)];

I do not know how other solvers manage "inf".

**Comment by rmtfleming** [comment]
pls submit pull request with fix

**Comment by laurentheirendt** [comment]
@bheavner , you seem to have a good idea on how to solve this issue. Could you please open a pull-request (PR) with the suggested changes in the code?

Guidelines on how to contribute are [here](https://github.com/opencobra/cobratoolbox/blob/master/.github/CONTRIBUTING.md).

Please let me know if you are running into any issues.
