### ISSUE TITLE
Bug in writeCbModel/writeSBML

### ISSUE THREAD

**Issue by simas232** [opencobra/cobratoolbox#161]
The function fails to export gene-reaction association information correctly when genes with unsupported characters are present in the model. To my experience, unsupported characters are ",", "-" and "|".

All reactions, associated with unsupported characters containing genes, will not have any gene-reaction association information in exported FBC v2 file. The gene list in FBC v2 file, however, is unchanged.

This bug can be circumvented by removing/replacing unsupported characters in model.genes and model.grRules before using writeCbModel function.

**Comment by syarra** [comment]
@simas232, you seem to have a good idea on how to solve this issue. Could you please open a pull-request (PR)  with the suggested changes in the code?
[This link](https://help.github.com/articles/creating-a-pull-request/) can help you in the process of creating a PR.

**Comment by laurentheirendt** [comment]
Hi @almut-heinken , may you help us out here? I guess you might know what to change.

I can help you getting a PR submitted.

Thanks.

**Comment by laurentheirendt** [comment]
@tpfau, may you look into this?

**Comment by tpfau** [comment]
This will be part of the SBML rewrite as soon as we have decided on a model structure :)

**Comment by tpfau** [comment]
this is solved in the latest SBML update.
