### ISSUE TITLE
solveCobraLPCPLEX - make sure that these errors are actually thrown as errors

### ISSUE THREAD

**Issue by maikeaurich** [opencobra/cobratoolbox#165]
Dear Laurent, Sylvain
this seems to be an error rather than a warning: 

solveCobraLPCPLEX found and returned a solution. 
Optimal solution found, Objective 0.11222 
Elapsed time is 473.701875 seconds. 
[Warning: FBA problem error: Invalid input !!!!] 

Best Maike

**Comment by laurentheirendt** [comment]
Closing as fixed by PR #336 .
