### ISSUE TITLE
Potential Bug in design/createBilevelMILPproblem.m

### ISSUE THREAD

**Issue by cladelpino** [opencobra/cobratoolbox#167]
Lines 124-126:

% Number of inner problem primal varibles with no integers associated with
% them & not part of the special constraint set

n_nint = n - n_int - sum(sel_ic);

 This assumes there is no intersection between "variables with integers" (KO candidates) associated and "specially constrained".

 This is handled differently when Inint is constructed: Inint = selMatrix(~sel_int & ~sel_ic);, where "intersections" are accounted for.

 If there is any reaction that is in both sets in the user input, this will trigger an horzcat error in the corresponding matrix construction line: 

A_bl = [A_bl; Inint sparse(n_nint,m+n+2*n_int+n_ic+2*n_m)];  

Potential Solution: If there shouldn't be any intersections (Specially constrained reactions aren't KO candidates frequently), this should be tested explicitly over user input.

**Comment by laurentheirendt** [comment]
Thanks @cladelpino. May you submit a pull request with your solution?

**Comment by snmendoz** [comment]
@laurentheirendt I will fix this. If you want, you can assign this task to my username.

**Comment by laurentheirendt** [comment]
Great to hear that @snmendoz 🎉  We are looking forward to your PR!

**Comment by snmendoz** [comment]
@laurentheirendt this was already fixed in the function createBilevelMILPproblem.m and it is working properly as shown in the optKnock tutorial I provided. This issue should be closed.
