### ISSUE TITLE
solveCOBRALPCPLEX comment remarks

### ISSUE THREAD

**Issue by marouenbg** [opencobra/cobratoolbox#173]
please comment
line 86
line 94
line 96

**Comment by rmtfleming** [comment]
?

**Comment by marouenbg** [comment]
It is actually more than that
it is a unsolved conflict in the function

**Comment by rmtfleming** [comment]
Please explain clearly the issue.

**Comment by marouenbg** [comment]
in solveCOBRALPCPLEX.m there is a git conflit

e.g.

`<<<<<<< HEAD
% Ronan Fleming 10 June 08
%               20 Mar  09  min norm can be specific to each variable
%               12 Jul  09  more description of basis reuse
%               23 Oct  09  ILOG-CPLEX matlab simple interface by default
%                           See solveCobraCPLEX for full control of CPLEX
%                           12.1 via API
=======
% Ronan Fleming
>>>>>>> 394d240372260c2130fde598cfba2e430692bd43`

**Comment by rmtfleming** [comment]
Where? not here:
https://github.com/opencobra/cobratoolbox/blob/master/solvers/solveCobraCPLEX.m

**Comment by marouenbg** [comment]
solveCobraLPCPLEX not solveCobraCPLEX

**Comment by rmtfleming** [comment]
Thanks
@laurentheirendt please look into this because I think you were editing it at the same time as I was.
https://github.com/opencobra/cobratoolbox/blob/master/solvers/solveCobraLPCPLEX.m

**Comment by laurentheirendt** [comment]
I will submit a PR soon.

**Comment by laurentheirendt** [comment]
PR submitted.
