### ISSUE TITLE
Issue with parseCVTerms.m for models generated through gapseq

### ISSUE THREAD

**Issue by TBerg42** [opencobra/cobratoolbox#1763]
I have been trying to reconstruct metabolic models using gapseq, a tool for automatic reconstruction of microbial metabolic models (see [here](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02295-1#citeas) in literature).
The models are exported in standard SBML level 3 format and I have tested them using:  http://sbml.org/Facilities/Validator/ and they passed as valid SBML.
However, when I try to do some further analysis using COBRA I run into the following problem when loading the models:
___
 model = readCbModel('GeneratedModel.xml')

Output argument "qualifiers" (and maybe others) not assigned during call to "getDataBases".

Error in parseCVTerms (line 27)
[databases,identifiers,relations] = cellfun(@getDataBases, {CVTerms.resources},
{CVTerms.qualifier},'UniformOutput',0);

Error in readSBML (line 121)
        [databases,identifiers,qualifiers] = cellfun(@parseCVTerms, cvterms,'UniformOutput',0);

Error in readCbModel (line 211)
        model = readSBML(fileName,defaultBound);
___
When I try it on other models in SBML format from literature it seems to work fine. There are two example models generated with gapseq [here](https://github.com/jotech/gapseq/tree/master/toy) (ecoli.xml.gz and myb71.xml.gz), I have also attached them for convenience.  Is it something to do with the structure of the models that I would need to change in order to successfully load them using readCbModel? 

[Sample_models.zip](https://github.com/opencobra/cobratoolbox/files/6411798/Sample_models.zip)

**I hereby confirm that I have:**
- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

**Comment by tpfau** [comment]
Hi,
I just opened a pull request to address this.
Seems like either we used an old style identifiers.org pattern, since I hadn't seen the pattern they now use in any models. 
If you have a look at my pr (#1764) you can temporarily edit the file on your machine till the PR is merged. 
I tested it with your ecoli model and the patch seems to work.

**Comment by TBerg42** [comment]
@tpfau 
Perfect, thank you very much for your prompt response. 
I tried the change and it seems to work fine now.
