### ISSUE TITLE
changeCobraSolver: Solver ibm_cplex is installed but not working properly.

### ISSUE THREAD

**Issue by wh960823** [opencobra/cobratoolbox#1799]
*Please include a short description of problem here*

**I hereby confirm that I have:**

- [ ] Tried to solve the issue on my own
- [ ] Retried to run my code with the latest version of The COBRA Toolbox
- [ ] Checked that a similar issue has not already been opened

*(Note: You may replace [ ] with [X] to check the box)*

**Comment by rmtfleming** [comment]
what version of cplex? What is the error exactly? Did you search the google group for answers?
