### ISSUE TITLE
bug in addReaction() function

### ISSUE THREAD

**Issue by jtyurkovich** [opencobra/cobratoolbox#19]
Hi,

I was attempting to build my own COBRA model from scratch (modeling glycolysis for class), entering in equations using the addReaction() function and ran into problems with reversible/irreversible reaction bounds. Basically, I used the flag to add reversible reactions, but at least in Matlab that doesn't work -- it seems to be a bug. The flag does change the direction of the reaction arrow when printed to the command window and update the model.rev vector, but it does not update the model.lb vector (which is what actually specifies the reversibility of a reaction). I looked at the code for addReaction() and believe I found the problem and fixed it. 

Here is the relevant code within the addReaction function:

``` Matlab
0104 % Missing arguments
0105 if (nargin < 6 | isempty(lowerBound))
0106     if (oldRxnFlag)
0107         lowerBound = model.lb(rxnID);
0108     else
0109         if (revFlag)
0110             lowerBound = min(model.lb);
0111             if isempty(lowerBound)
0112                 lowerBound=-1000;
0113             end
0114         else
0115             lowerBound = 0;
0116         end
0117     end
0118 end
```

In line 110, the lower bound is set to the minimum value in the vector of lower bounds already set in the model. In lines 111-113, the lower bound is only set to -1000 if there is already a reaction with lower bound -1000. In other words, the first reaction entered must be a reversible reaction in order for all subsequent reversible reactions to have the correct lower bound. If on the other hand, the first reaction entered is irreversible (as in my case when adding the glycolysis reactions) with lowerBound = 0, the lower bound would be set to the lower bound of that first reaction (lowerBound = 0). Thus, adding reversible reactions (lowerBound = -1000) after adding the first reaction as irreversible (lowerBound = 0) will result in an error for the lower bound of all subsequent reversible reactions.

I believe this bug would be fixed by adding another conditional statement that only uses the minimum of the model.lb vector as the new lower bound if there is a reversible reaction already present (lines 110-112):

``` Matlab
0104 % Missing arguments
0105 if (nargin < 6 | isempty(lowerBound))
0106     if (oldRxnFlag)
0107         lowerBound = model.lb(rxnID);
0108     else
0109         if (revFlag)
0110             if sum(model.rev) ~= 0
0111                 lowerBound = min(model.lb);
0112             end
0113             if isempty(lowerBound)
0114                 lowerBound=-1000;
0115             end
0116         else
0117             lowerBound = 0;
0118         end
0119     end
0120 end
```

I made this change in my version of addReaction(), and it has so far worked without any bugs. This change still ensures that the minimum reaction bound is set to the present minimum (i.e. if the minimum bound was specified to be something other than -1000 this will preserve that), which I believe was the goal of the original code.

Thanks,

James

**Comment by rmtfleming** [comment]
model.rev will be depreciated

**Comment by aebrahim** [comment]
Nice. I had issues with reversibility in cobrapy and wanted to make sure
our solutions were consistent. Rev really is redundant information. In
cobrapy it is now a computed property.

**Comment by laurentheirendt** [comment]
@rmtfleming , how shall we proceed with this? Thanks.

**Comment by rmtfleming** [comment]
model.rev should be depreciated in the next month

**Comment by tpfau** [comment]
While not yet completely removed from all parts, rev is deprecated now, and most functions are updated to extract rev from model.lb < 0. The concrete issue named is solved so this can be closed.
