### ISSUE TITLE
cplex incompatibility with matlab

### ISSUE THREAD

**Issue by flrvm** [opencobra/cobratoolbox#190]
@laurentheirendt  

CPLEX version `12.6.2`
UBUNTU version `16.04`
MATLAB version `2015b`

**Small example (code):**
% 1.1 Load model generic
genericPath = '~/work/sbgCloud/data/models/unpublished/Recon3/';
genericFile = '2016_07_13_Recon3.mat';
load(strcat(genericPath, genericFile));
model = modelRecon3;
clear modelRecon3 modelRecon3model
% test feasability
solFBA_init = optimizeCbModel(model);

**Result:**
Warning: The function 'cplexlink1262' returned an mxArray with non-temporary scope. 
> In Cplex/subsref
  In solveCobraLP (line 1304)
  In optimizeCbModel (line 213)

**Comment by laurentheirendt** [comment]
Issue is reproducible with `MATLAB15b`/ `CPLEX 12.6.2`,  `MATLAB15b`/`CPLEX 12.6.3`, and `MATLAB15b`/`CPLEX 12.7.0`.

The output `solFBA_init` is the same though as with `MATLAB14b`/`CPLEX 12.6.2`, `MATLAB16a`/`CPLEX 12.6.2`, `MATLAB16a`/`CPLEX 12.6.3`, or `MATLAB16a`/`CPLEX 12.7.0` (no warnings thrown).

When using the `CPLEX` solver, please make sure to set the solver properly with
```Matlab
changeCobraSolver('ibm_cplex')
```
The warning can be safely ignored. Suggestion is to use either `MATLAB14b`/`CPLEX 12.6.2` or `MATLAB16a` with any version of `CPLEX 12.6.2+`. Please note that `CPLEX 12.6.2+` is **not** compatible with `MATLAB16b`.

@flrvm , thanks for reporting this. Closing for now.
