### ISSUE TITLE
Path to mosek

### ISSUE THREAD

**Issue by CcileMoul1** [opencobra/cobratoolbox#1914]
Hi,
I installed CobraToolbox and the solver Mosek (as well as Gurobi) on my **Linux** computer by following the instructions [here](https://opencobra.github.io/cobratoolbox/latest/installation.html#mosek). I tested the command
```
/opt/mosek/9.3/tools/platform/linux64x86/bin/msktestlic
```
and I had the following result, indicating that Mosek is well installed (I suppose)
```
Mosek license manager: License path: /opt/mosek/
Mosek license manager:  Checkout license feature 'PTS' from flexlm.
Mosek license manager:  Checkout time 0.01. r: 0 status: 0
Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : LO (linear optimization problem)
  Constraints            : 1               
  Cones                  : 0               
  Scalar variables       : 5000            
  Matrix variables       : 0               
  Integer variables      : 0               

Optimizer started.
Presolve started.
Eliminator started.
Freed constraints in eliminator : 0
Eliminator terminated.
Eliminator started.
Freed constraints in eliminator : 0
Eliminator terminated.
Eliminator - tries                  : 2                 time                   : 0.00            
Lin. dep.  - tries                  : 0                 time                   : 0.00            
Lin. dep.  - number                 : 0               
Presolve terminated. Time: 0.00    
Optimizer terminated. Time: 0.00    

************************************
A license was checked out correctly.
************************************
```

As said in the instructions, the path to Mosek is `opt/mosek/9.3/tools/platform/linux64x86/bin/` or subsequence of this path but when I run `initCobraToolbox`, the value of MOSEK_PATH is `...cobratoolbox/src/base/solvers/mosek`, even when I change this value in the file `.bashrc` (not in the instructions but I tried it). 

As those two pathes are different, `initCobraToolbox` cannot find and test Mosek 
(extract of the message of `initCobraToolbox`)
```
[glpk] Primal optimality condition in solveCobraLP satisfied.Could not find installation of mosek, so it cannot be tested
Could not find installation of matlab, so it cannot be tested
```
How do I solve that ?

Thanks, 
Best regards
Ccile

**Comment by rmtfleming** [comment]
Thanks, this should be fixed in the develop and master branch now.

**Comment by CcileMoul1** [comment]
I confirm that it works now (at least on Linux).

Thanks to you
