### ISSUE TITLE
Error in FBAsol.y length when running optimizeCbModel(model, 'max', 1e-6)

### ISSUE THREAD

**Issue by dayena123** [opencobra/cobratoolbox#1915]
**Error in FBAsol.y length** when running FBAsol = optimizeCbModel(model, 'max', 1e-6);

**I hereby confirm that I have:**

- [x] Tried to solve the issue on my own
- [x] Retried to run my code with the latest version of The COBRA Toolbox
- [x] Checked that a similar issue has not already been opened

*(Note: You may replace [ ] with [X] to check the box)*

**Comment by dayena123** [comment]
**** @rmtfleming

**Comment by rmtfleming** [comment]
fixed in master version
