### ISSUE TITLE
COBRA Toolbox submodules

### ISSUE THREAD

**Issue by svijayakumar32** [opencobra/cobratoolbox#1936]
Hi 

I've checked similar on here but I haven't been able to resolve it. I am trying to run initCobraToolbox and receive the following error -

>> initCobraToolbox
/usr/bin/sh: \uni\homes\23\username\My Documents\cobratoolbox\.tmp\PortableGit-2.13.3\mingw64/libexec/git-core\git-submodule: No such file or directory
Error using initCobraToolbox (line 233)
The submodules could not be initialized.

**I hereby confirm that I have:**

- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

Thanks
Supreeta

**Comment by svijayakumar32** [comment]
After running git clone, I get the following output - 
>> initCobraToolbox
(git is not installed, attempting to install GitBash).
 > Downloading gitBash archive (this may take a while) ... Done.
 > Extracting the gitBash archive (this may take a while) ... Done.
 > gitBash successfully installed.
Output argument "versionGit" (and maybe others) not assigned during call to "initCobraToolbox>checkGit".

Error in initCobraToolbox (line 122)
[installedGit, versionGit] = checkGit();

**Comment by rmtfleming** [comment]
https://opencobra.github.io/cobratoolbox/stable/installation.html

On Wed, 16 Feb 2022 at 14:37, Supreeta Vijayakumar
***@***.***> wrote:
>
> After running git clone, I get the following output -
>
> initCobraToolbox
> (git is not installed, attempting to install GitBash).
> Downloading gitBash archive (this may take a while) ... Done.
> Extracting the gitBash archive (this may take a while) ... Done.
> gitBash successfully installed.
> Output argument "versionGit" (and maybe others) not assigned during call to "initCobraToolbox>checkGit".
>
> Error in initCobraToolbox (line 122)
> [installedGit, versionGit] = checkGit();
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



-- 
--
Mr. Ronan MT Fleming B.V.M.S. Dip. Math. Ph.D.
----------------------------------------------------------------------------
Associate Professor,
School of Medicine,
National University of Ireland, Galway.
&
Assistant Professor,
Division of Systems Biomedicine and Pharmacology,
Leiden Academic Centre for Drug Research,
Faculty of Science,
Leiden University.
https://www.universiteitleiden.nl/en/staffmembers/ronan-fleming
&
H2020 Project Coordinator,
Systems Medicine of Mitochondrial Parkinson’s Disease,
http://sysmedpd.eu
----------------------------------------------------------------------------
Peer-reviewed publications: https://goo.gl/FZPG23
Mobile:  +353 852 109 806
Skype: ronan.fleming
----------------------------------------------------------------------------
(This message is confidential and may contain privileged information.
It is intended for the named recipient only. If you receive it in
error please notify me and permanently delete the original message and
any copies.)
