### ISSUE TITLE
rMTA gives more bMTA scores than expected

### ISSUE THREAD

**Issue by OAshkar** [opencobra/cobratoolbox#1945]
*Please include a short description of problem here*
I have a problem running rMTA. The thing is I have no array of size 6663 before I run rMTA(), so I don't know where this number came from. 

I need to identify the problem so I can fix it.
Thank you

**I hereby confirm that I have:**

- [x] Tried to solve the issue on my own
- [x] Retried to run my code with the latest version of The COBRA Toolbox
- [x] Checked that a similar issue has not already been opened

*(Note: You may replace [ ] with [X] to check the box)*

> 
> ===================================
> ========  rMTA algorithm  =========
> ===================================
> Step 0: preprocessing: 
> Calculate Gene Knock-out matrix
> 100%    [........................................]
> 	GeneKOMatrix calculated
> -------------------
> Step 1 in progress: the best scenario 
> 	Start rMTA best scenario case for alpha = 0.66 
> 	cplex model for MTA built
>     MIQP Iterations for bMTA
> 212                 Vres.bMTA{i_alpha}(:,i) = v_res;
> Unable to perform assignment because the size of the left side is 6663-by-1 and the size of the right side is 6471-by-1.
> 
> Error in rMTA (line 212)
>                 Vres.bMTA{i_alpha}(:,i) = v_res;

EDIT:
This problem does not seem to occur in MTA(). But still I want to use rMTA().

**Comment by lvalcarcel** [comment]
Dear @OAshkar ,

Is there any 'temp_rMTA.mat' file in your directory? If so, delete it.

If not, could you please attach the input that you have used for the tool? I would like to replicate the error in order to fix it.

**Comment by OAshkar** [comment]
Thanks a lot. It was the issue indeed! I am closing this issue
