### ISSUE TITLE
#Error : unrecognized field name "dual"

### ISSUE THREAD

**Issue by SiYeon-Ju** [opencobra/cobratoolbox#2058]
Hi, 
When i run "optimizeCbModel" function with loopless on the latest version , I got the following error.
but, I tried to replace the 'optimizeCbModel.m' file with that of the previous version, it can be run. 
how can i fix it?

Thanks! 

-> Matlab R2022b / Gurobi 9.5.2 / Cobratoolbox 3

input)
model_sol = optimizeCbModel(model, 'max', 0, 0 );

Output)
Unrecognized field name "dual".
Error in optimizeCbModel (line 726)
if isemty(solution.dual)

- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

**Comment by ithiele** [comment]
Fixed in new master version
