### ISSUE TITLE
How to compute the C stoichiometric matrix with Julia

### ISSUE THREAD

**Issue by jialin3299** [opencobra/cobratoolbox#2088]
*How to compute the C stoichiometric matrix with Julia*

Hi, when I used the COBRA Toolbox to generate the personalized community model, the C matrix replaced the original A matrix. When I tried to calculate the metabolic flux of C matrix with Julia, the code reported an error, which showed that there was no C matrix in the model. I wonder if the error was caused by the change of the internal structure of the model. Now I use FVA in the Microbiome Modeling Toolbox to calculate metabolic flux. The calculation of 10 models with an average of about 20MB is slow and shows insufficient memory.
Can Julia calculate C matrix now?

The specific error displayed using Julia 0.6.4 is:
ERROR: LoadError: Matrix 'C' dose not exist in 'microbiota_model'.

**I hereby confirm that I have:**
- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

**Comment by rmtfleming** [comment]
Post this message to COBRA.jl
