### ISSUE TITLE
Faulty metabolite renaming in checkCobraModelUnique

### ISSUE THREAD

**Issue by andrevo** [opencobra/cobratoolbox#21]
I am having issues running checkCobraModelUnique on my model - 'cell content indices must be greater than 0' at line 51, when renaming metabolites. By the looks of it, this can be traced back to line 49 - the function is looking through the model's reactions for a given metabolite, which doesn't seem right. Then, in line 51, it's trying to rename a reaction, while it should be trying to rename a metabolite.

**Comment by rmtfleming** [comment]
If you're sure it is a problem with the code and not your model, please submit a pull request with your fix.

**Comment by syarra** [comment]
@andrevo, any news?

**Comment by andrevo** [comment]
I'm not 100% sure which model I was using when I experienced the issue, 
and if I even still have it on my computer, so I'm not sure if I can try 
to replicate the original problem. I'll try to find out and get back to you.

André
