### ISSUE TITLE
How can the result file be converted to a readable file?

### ISSUE THREAD

**Issue by qkqk-hub** [opencobra/cobratoolbox#2215]
Hello, I would like to ask you a question:
I get a lot of.mat result files in the refinedReconstructions folder. How do I convert them to xlsx or csv for easy viewing?

Here is the result file I generated in the refinedReconstructions folder:
![image](https://github.com/opencobra/cobratoolbox/assets/54273704/8d6d9594-ca68-4191-8325-380c5453a2b9)

Thank you for your reply!

**Comment by almut-heinken** [comment]
Hello, these are the generated reconstructions. You have to option to also export them as SBML files, however, xlsx is not available. The best way to view them is to import them back into Matlab via readCbModel.

**Comment by qkqk-hub** [comment]
Ok, I understand, thank you for your reply!
