### ISSUE TITLE
Error using initCobraToolbox 

### ISSUE THREAD

**Issue by 2132030** [opencobra/cobratoolbox#2231]
initCobraToolbox

      _____   _____   _____   _____     _____     |
     /  ___| /  _  \ |  _  \ |  _  \   / ___ \    |   COnstraint-Based Reconstruction and Analysis
     | |     | | | | | |_| | | |_| |  | |___| |   |   The COBRA Toolbox - 2024
     | |     | | | | |  _  { |  _  /  |  ___  |   |
     | |___  | |_| | | |_| | | | \ \  | |   | |   |   Documentation:
     \_____| \_____/ |_____/ |_|  \_\ |_|   |_|   |   http://opencobra.github.io/cobratoolbox
                                                  | 

 > Checking if git is installed ...  Done (version: 2.34.1).
 > Checking if the repository is tracked using git ...  Done.
 > Checking if curl is installed ...  Done.
 > Checking if remote can be reached ...  Done.
 > Initializing and updating submodules (this may take a while)...Error using initCobraToolbox (line 247)

I get this ERROR in MATLAB 2021b: Failed to retrieve submodules paths.

**Comment by farid-zare** [comment]
Hello, 
Thanks for your feedback. 
Are you still facing this problem ? 
If so, can you make sure you are following this guideline for installation ? 
https://opencobra.github.io/cobratoolbox/stable/installation.html
