### ISSUE TITLE
bug adding metCHEBIDD in addMetabolite.m

### ISSUE THREAD

**Issue by jwm1** [opencobra/cobratoolbox#224]
In addMetabolite.m the lines 214 to 216 should use metCHEBIID not metChEBIID otherwise the model.metCHEBIID is not updated.

```
if isfield(model,'metChEBIID')
            model.metChEBIID{end+1,1} = CHEBIID{i};
end
```

**Comment by tpfau** [comment]
This is actually something that should be adjusted in other functions as well. e.g. xls2model also refers to metChEBIID. 
Its also referred to in this way in parts of the documentation.

**Comment by laurentheirendt** [comment]
Hi @jwm1, may you follow @tpfau's advice and submit a pull-request (PR) with the suggested changes in the code?

Guidelines on how to contribute are [here](https://github.com/opencobra/cobratoolbox/blob/master/.github/CONTRIBUTING.md).

Please let me know if you are running into any issues.

**Comment by jwm1** [comment]
>may you follow @tpfau's advice and submit a pull-request (PR) with the suggested changes

yes, I will do this, when I've worked out how.

James

**Comment by laurentheirendt** [comment]
Hi @jwm1 ,

Please let either @syarra or myself know if you need any help with this.

We are here to help you!
