### ISSUE TITLE
DEMETER can be used for metabolic network optimization beyond intestinal microbiota?

### ISSUE THREAD

**Issue by hzau-gzy** [opencobra/cobratoolbox#2250]
*Please include a short description of problem here*
DEMeter is a metabolic network optimization method developed for gut microbiota, but can DEMeter also be used to optimize the metabolic network of microorganisms other than gut microbiota？
**I hereby confirm that I have:**

- [ ] Tried to solve the issue on my own
- [ ] Retried to run my code with the latest version of The COBRA Toolbox
- [ ] Checked that a similar issue has not already been opened

*(Note: You may replace [ ] with [X] to check the box)*

**Comment by rmtfleming** [comment]
Heirendt, L., Arreckx, S., Pfau, T. et al. Creation and analysis of biochemical constraint-based models using the COBRA Toolbox v.3.0. Nat Protoc 14, 639–702 (2019). https://doi.org/10.1038/s41596-018-0098-2

**Comment by almut-heinken** [comment]
Hello, in principle, DEMETER can be used for any bacteria. For non-human-associated organisms, though, you may consider reconstructing additional pathways (carbon sources, fermentation) currently not captured by the pipeline.
