### ISSUE TITLE
extractSubNetwork doesn't return rxnNames

### ISSUE THREAD

**Issue by bheavner** [opencobra/cobratoolbox#24]
The subModel structure generated by this function does not include a rxnNames field. One fix could be to add something like this:

[~, ~, IB] = intersect(subModel.rxns, model.rxns, 'stable');
subModel.rxnNames = model.rxnNames(IB);

**Comment by rmtfleming** [comment]
pls make pull request

**Comment by laurentheirendt** [comment]
@bheavner , you seem to have a good idea on how to solve this issue. Could you please open a pull-request (PR) with the suggested changes in the code?

Guidelines on how to contribute are [here](https://github.com/opencobra/cobratoolbox/blob/master/.github/CONTRIBUTING.md).

Please let me know if you are running into any issues.

**Comment by stefaniamagg** [comment]
@laurentheirendt This issue seems to have already been fixed by Srikiran C on 7/15/14. From src\extractSubNetwork.m:
```
%extractSubNetwork Extract subnetwork model
%
% subModel = extractSubNetwork(model,rxnList,metList)
%
%INPUTS
% model     COBRA model structure
% rxnList  Reaction list for the subnetwork to be extracted
%
%OPTIONAL INPUTS
% metNames  Metabolite list for the subnetwork to be extracted
%
%OUTPUT
% subModel  COBRA model of subnetwork
%
% Markus Herrgard 12/11/06
%
% Srikiran C 7/15/14
% - Replaced rxnNames with rxnList as model.rxnNames is different from
% model.rxns, and model.rxns is used to select the subnetwork.
% - Replaced metNames with metList, to avoid similar confusion.
% - Added the fields - rxnNames, rules and metCharge to subModel.
```

**Comment by laurentheirendt** [comment]
Thank you @stefaniamagg . Closing now.
