### ISSUE TITLE
spelling error in removeRxns

### ISSUE THREAD

**Issue by dayena** [opencobra/cobratoolbox#241]
*(Note: You may replace [ ] with [X] to check the box)*

**I hereby confirm that I have:**

- [x] Run `git pull` and retried to run my code
- [x] Checked that a similar issue hasn't already been filed

[At line 71 there is a spelling error mfileds --> should be mfields]

### Reproduction steps or steps that explain the enhancement

1. [*First Step*]
2. [*Second Step*]
3. [*Other Steps...*]

### Expected behavior

[*Describe the expected behavior here*]

### Current/observed behavior

[*Describe the currently observed behavior here*]

### Issue nature (N/A for enhancement)

- [ ] `MATLAB` crashed. If yes, please include a crash report and details how you launch `MATLAB`.
- [x] Performance issue. If yes, please include more details (see above)
- [ ] Issue triggered through a specific action. If yes, please describe what you were doing in more detail.

### System information

- ***`pathdef.m` and `startup.m`*** [*Provide details here, e.g. which directories are included and where they are stored*]
- ***`MATLAB` version:*** [*Enter MATLAB version here*]
- ***OS and version:*** [*Enter OS name and OS version here*]
- ***Installed solvers*** [*Provide a list of installed solvers here*]

### Additional information (N/A for enhancement)

- [ ] Problem might be related to external program (e.g., solver) and **not** The COBRA Toolbox
- [x] Problem started happening recently, didn't happen in an older version of The COBRA Toolbox
- [x] Problem can be reliably reproduced, doesn't happen randomly
- [ ] Problem happens for all COBRA models, not only some

**Comment by laurentheirendt** [comment]
Thanks @dayena .
