### ISSUE TITLE
optimizeCbModelNLP

### ISSUE THREAD

**Issue by hsnguyen** [opencobra/cobratoolbox#25]
Hi, I'm trying to implement non-linear objective functions for FBA using cobra toolbox. Looks like optimizeCbModelNLP() is the one I need but it didn't work. I use fmincon() in MATLAB as the nonlinear solver and based on script optimizeCbModelNLP, i created for myself a FBA model with max-Biomass-per-flux-unit (doi:10.1038/msb4100162) as the objective function. 
The problem is that by using 100 or even 500 initial random points, the optimization solutions still not converged (values of solution.f were different from each run though they're very close together). There are also warnings shown up 'Matrix is close to singular or badly scaled...'. Any suggestion for that?

**Comment by rmtfleming** [comment]
fmincon is not a good optimiser. Check out mosek.com
