### ISSUE TITLE
change default branch to develop

### ISSUE THREAD

**Issue by marouenbg** [opencobra/cobratoolbox#258]
*(Note: You may replace [ ] with [X] to check the box)*

**I hereby confirm that I have:**

- [X ] Run `git pull` and retried to run my code
- [ X] Checked that a similar issue hasn't already been filed

I suggest to change the default branch of the cobratoolbox to develop.
That would avoid pushing PRs to master by default, while it doesn't change the behavior of git pull.

**Comment by laurentheirendt** [comment]
Thanks for your suggestion. 

However, we will keep the current standard branching model with the `master` branch being the **default** branch (stable release branch) and the `develop` branch being the experimental/latest developments branch.

Future development guidelines will include specific instructions to help developers raise the PRs against the `develop` branch.
