### ISSUE TITLE
readCbModel error

### ISSUE THREAD

**Issue by marouenbg** [opencobra/cobratoolbox#265]
*(Note: You may replace [ ] with [X] to check the box)*

**I hereby confirm that I have:**

- [X ] Run `git pull` and retried to run my code
- [ X] Checked that a similar issue hasn't already been filed

A few users in the Cobra google group reported errors with readCbModel. I noticed ^M characters in the code like in commented lines 87, 171 and, 177 in https://github.com/opencobra/cobratoolbox/blob/master/src/io/readCbModel.m#L87

Could that be the reason of the errors?

**Comment by laurentheirendt** [comment]
`^M` is a carriage-return character from a DOS operating system (Windows). This should not cause any error.

May you provide more information on the error thrown?

**Comment by marouenbg** [comment]
my bad, I will follow up with issue later.
