### ISSUE TITLE
dynamicFBA substrate reactions need to be in alphabetical order

### ISSUE THREAD

**Issue by labhset1** [opencobra/cobratoolbox#273]
*(Note: You may replace [ ] with [X] to check the box)*

**I hereby confirm that I have:**

- [X] Run `git pull` and retried to run my code
- [X] Checked that a similar issue hasn't already been filed

When we have multiple substrate reactions to be tracked while doing dynamicFBA, they need to be in alphabetical order otherwise the initial concentration are assigned incorrectly. This is due to the way code is written in lines 73 and 75. 
 Following is the fix
[~, substrateMatchInd] = ismember(substrateRxns,excRxnNames); % line 73
concentrations = zeros(length(excRxnNames),1); % line 74
concentrations(substrateMatchInd) = initConcentrations; % line 75

**Comment by laurentheirendt** [comment]
@marouenbg, may you have a look at this? Thanks.

**Comment by marouenbg** [comment]
Indeed, thanks for pointing this out, you can also change the order of the legend string at the last line of the function.

@labhset1 you would like to do a PR for it or should I do it on your behalf?

**Comment by labhset1** [comment]
Hi,
Its not just about legends. The assignment of initial concentrations also is incorrect. The order of the given concentrations remains the same but the substrate they get assigned to gets sorted. I have correction given for the line 73,74,75 in my initial post. What is PR?

**Comment by marouenbg** [comment]
ok then. PR is a pull request, where you can change these lines you mentioned in the COBRA toolbox source code. You can contribute to the toolbox through PRs.

Have a look here
https://help.github.com/articles/creating-a-pull-request/

**Comment by laurentheirendt** [comment]
@marouenbg , may you put in the PR? Thanks.

**Comment by marouenbg** [comment]
ok ASAP!

**Comment by laurentheirendt** [comment]
Closing as fixed by PR #342.
