### ISSUE TITLE
optimizeCbModelNLP calls solveCobraNLP with invalid parameter

### ISSUE THREAD

**Issue by tpfau** [opencobra/cobratoolbox#333]
**I hereby confirm that I have:**

- [X] Run `git pull` and retried to run my code
- [X] Checked that a similar issue hasn't already been filed

As just raised by Payam Setoodeh on the cobratoolbox mailing list, there is a problem in optimizeCbModelNLP line 76. The solve function is called with a parameter that is not specified in the function. I had a look into the history and even before the reorganization, this piece of code was not altered, so it seems that this problem existed even before moving to github and only comes up now. 
Either the optimizeCbModelNLP function or the solveCobraNLP function will have to be adjusted.

### Reproduction steps or steps that explain the enhancement
load any model as model.
Than:
1. optimizeCbModelNLP(model)

### Expected behavior

Solving the NLP problem.

### Current/observed behavior

> Error using solveCobraNLP (line 104)
> intTol is not a valid optional parameter

> Error in optimizeCbModelNLP (line 79)
>    solNLP = solveCobraNLP(NLPproblem, 'printLevel', printLevel, 'intTol', 1e-7, 'iterationLimit', majorIterationLimit);
>    %New function call

### Issue nature (N/A for enhancement)

- [X ] Issue triggered through a specific action. If yes, please describe what you were doing in more detail.

### System information

NA

### Additional information (N/A for enhancement)

- [X] Problem can be reliably reproduced, doesn't happen randomly
- [X] Problem happens for all COBRA models, not only some

**Comment by laurentheirendt** [comment]
Closing as solved by PR #335.
