### ISSUE TITLE
some functions (like extractSubNetwork) miss model fields

### ISSUE THREAD

**Issue by akaviaLab** [opencobra/cobratoolbox#343]
*(Note: You may replace [ ] with [X] to check the box)*

**I hereby confirm that I have:**

- [X ] Checked that a similar issue hasn't already been filed

extractSubNetwork (and possibly other functions) have a problem where the model fields are coded in the function.
if (isfield(model,'geneNames'))
    subModel.geneNameRules = model.geneNameRules(selRxns);
    subModel.geneNames = model.geneNames(selGenes);
end
if (isfield(model,'subSystems'))
    subModel.subSystems = model.subSystems(selRxns);
end
if (isfield(model,'rxnNames'))
    subModel.rxnNames = model.rxnNames(selRxns);
end
if (isfield(model,'rules'))
    subModel.rules = model.rules(selRxns);
end

The problem is that in case of models that have additional fields (such as RECON 2.04), the functions won't change them.
removeRxns, lines 63-73 defines the fields to process, but we could expand the defintion to a global struct or function, or maybe part of every model

Then we could intersect with current model, and have code that would look something like:
modelOut.(rfields{i}) = model.(rfields{i})(selectRxns, :) for removing/selecting reactions and so forth.

If we can agree on a way of doing this, I'm willing to go over the code, find cases, and make sure they all use the updated version. I keep tripping on this when I use new functions, and then miss certain fields or something.

**Comment by tpfau** [comment]
This is part of an issue, we hope to address soonish (essentially, that additional model fields cannot clearly be associated with specific required fields). 
@syarra @laurentheirendt @rmtfleming 
I like the idea of a model field defining fields, which could be used to properly update fields and is flexible wrt future changes.

**Comment by laurentheirendt** [comment]
Thanks for solving this issue here, @tpfau! 👍
