### ISSUE TITLE
Gurobi 6 doesn't seem to be fully supported

### ISSUE THREAD

**Issue by akaviaLab** [opencobra/cobratoolbox#35]
While gurobi6 is supported as an option in changeCobraSolver.m, only gurobi5 is defined in solveCobraLP.m (starting at line 188). Setting the solver as gurobi6 results in problems in (for example) optimizeCbModel.m

**Comment by rmtfleming** [comment]
fixed

**Comment by akaviaLab** [comment]
A similar fix should probably be propogated to solveCobraMILP.m, solveCobraNLP.m and so on (I'm guessing solveCobra*). I don't understand the files, otherwise I'd fix them myself.
