### ISSUE TITLE
setQuantConstraints.m - variable `epsilon` is not used

### ISSUE THREAD

**Issue by jacekwachowiak** [opencobra/cobratoolbox#376]
*(Note: You may replace [ ] with [X] to check the box)*

**I hereby confirm that I have:**

- [X] Checked that a similar issue hasn't already been filed

[*Please include a short description of problem or enhancement here*]
The input variable `epsilon` in the file src/metabotools/setQuantConstraints.m is not used at all.

**Comment by laurentheirendt** [comment]
Fix by PR #455. Thanks @maikeaurich.
