### ISSUE TITLE
File existence failure when using cplex_direct in solveCobraLP.m

### ISSUE THREAD

**Issue by psalvy** [opencobra/cobratoolbox#39]
Hi there,

I was using the cobra Toolbox with cplex_direct as a solver, and I ran across an annoying warning on a Win 8.1 Machine:

```
Warning: File 'clone1.log' not found. 
  In solveCobraLP at 867
  In optimizeCbModel at 159
  In reduceModel at 102
  In pFBA at 89 
```

Since I was doing repeated optimization in a loop, this flooded my command window with useless messages. After a quick tour on Google, I discovered why this code, starting line 867 in cobratoolbox-master\solvers\solveCobraLP.m, bugged:

``` matlab
        if exist('clone1.log','file')
            delete('clone1.log')
        end
```

It suffers from the inconsistency of the exist() function in MATLAB for relative paths (see [here](http://www.mathworks.com/matlabcentral/answers/52705-test-existence-of-files-with-exist)).
A good fix I found ([on the mathworks forum here](http://www.mathworks.com/matlabcentral/answers/49414-check-if-a-file-exists)) is the following:

```
exist('clone1.log', 'file')                % ==> 2
exist(fullfile(cd, 'clone1.log'), 'file')  % ==> 0
```

Which, applied to our problem, gives:

``` matlab
        if exist(fullfile(cd, 'clone1.log'), 'file')
            delete('clone1.log')
        end
```

Which ensures you are using an absolute path, and removes the warning.

Hope this helps,

Pierre

**Comment by laurentheirendt** [comment]
[PR177](https://github.com/opencobra/cobratoolbox/pull/177) submitted.

Thanks @psalvy for the hint.
