### ISSUE TITLE
Redundant information in model structure

### ISSUE THREAD

**Issue by bertonoronha** [opencobra/cobratoolbox#40]
Hello all,

CobraToolBox's model structure carries redundant information in its structure. Occasionally, this causes problems when it comes to model maintenance and coherence between different representations of the same information. 
It would be convenient to remove the following elements:

rev - this information can be generated using the bounds of the reactions, and created on the fly if needed.

rules and rxnGeneMat - both these structures should also be removed as they can be generated from grRules

Best regards,
Alberto

**Comment by bbarker** [comment]
Redundant information I do not view as a problem in the model structure itself. Correct me if I'm wrong but I think grxnGeneMat and rules are actually generated from grRules when a model is imported from sbml.

rev is indeed [another long story](https://github.com/opencobra/cobratoolbox/pull/15)

**Comment by bertonoronha** [comment]
Actually, I really think that it is a problem. Aside from the fact that not everyone uses SBML, from the perspective of a Matlab user this is inconvenient. Every time one wants to change something on the structure, one has to keep in mind that there are several elements that contain that same information.

**Comment by bbarker** [comment]
It is a bit of an issue, but I am not sure the alternative is better. The
rxnGeneMat is used frequently during exploratory analyses and probably by a
lot of functions in the COBRA toolbox. so if is gotten rid of, a user would
have to generate it every time they want to use it. Furthermore, new users
may not know about it as easily. My impression, which could be wrong, is
that the gprules are not frequently changed by most COBRA users.

I'm not totally against the removals but want to point out there are some
potential side effects that may outweigh the benefits.

This may be totally wrong but could a listener be used to allow automatic
updates to the other fields?
http://www.mathworks.com/help/matlab/ref/handle.addlistener.html
I'm trying to find a solution that doesn't involve full blown abstraction
of the model and require getters and setters for all fields.

On Fri, Mar 13, 2015 at 4:49 AM, Alberto Noronha <notifications@github.com>
wrote:

> Actually, I really think that it is a problem. Aside from the fact that
> not everyone uses SBML, from the perspective of a Matlab user this is
> inconvenient. Every time one wants to change something on the structure,
> one has to keep in mind that there are several elements that contain that
> same information.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencobra/cobratoolbox/issues/40#issuecomment-78872215>
> .
>



-- 
Brandon Barker
brandon.barker@gmail.com

**Comment by bertonoronha** [comment]
Having a function that generates the matrix would solve this issue, I believe. And that would ensure that the matrix is coherent with the grRules.
