### ISSUE TITLE
convertSBMLToCobra can't close missing handle

### ISSUE THREAD

**Issue by cljacobs** [opencobra/cobratoolbox#42]
Minor issue with the latest update to convertSBMLToCobra (adding libSBML 5.11.0 support). 

The update commented out a few lines of code that opened progress bars (lines 78, 163, 195). This causes readCbModel to fail when the function then tries to close these handles, as the variables do not exist.

I'm not sure if the comments were introduced to prevent the progress bar appearance during testing, or if this reflects the intention to remove the bars from future releases. Either uncommenting the lines in question, or removing the subsequent calls of `close(h)` would fix the issue.

**Comment by rmtfleming** [comment]
Thanks, this will be fixed.

**Comment by syarra** [comment]
@rmtfleming, fixed?
