### ISSUE TITLE
Improper call to external function Volume() from MFE sampling

### ISSUE THREAD

**Issue by psalvy** [opencobra/cobratoolbox#466]
Hi guys,

I was looking into the MFE sampler coming from your collaboration with Ben Cousins, and I found out that your call to the volume estimation function `Volume(P,E,eps)` did not follow the paradigm switch in their code where P is now a structure rather than an array.

A proper fix would be to write in cobratoolbox\src\modelAnalysis\sampling\sampleCbModel.m, lines 166-194:
```matlab
A=[-eye(n,n);...
    eye(n,n)];
b=[-model.lb;...
    model.ub];

P.A = A;
P.b = b;
P.A_eq = model.S;
P.b_eq = model.b;
E=[];
if ~isfield(options,'eps')
    eps=0.15;
else
    eps=options.eps;
end

%get an intial point
FBAsolution = optimizeCbModel(model);
P.p = FBAsolution.x;

[volume,T,steps,r_steps] = Volume(P,E,eps);
```

I can issue a pull request if you are interested. 

Cheers,

Pierre

**Comment by laurentheirendt** [comment]
@psalvy , thank you for this. Yes, please put in a PR.

You can now contribute to The COBRA Toolbox using the recently released [MATLAB.devTools](https://github.com/opencobra/MATLAB.devTools). These tools will help you submit future pull requests with ease.

We are looking forward to your contributions!

cc: @bounciness

**Comment by psalvy** [comment]
Oh, pretty nifty !
I'll run additional tests to make sure I am not missing anything else and issue the PR using this cool new toy.

Cheers,

Pierre

**Comment by psalvy** [comment]
As a connected issue, the external code that is shipped with cobratoolbox for `makeBody.m`, and `preprocess.m`, even though probably not used in a common use-case, is also not aligned with this version of `Volume(P,E,eps)`.
Since this code is external, maybe rather than changing it myself it would be worth it to check with Ben Cousins ?

Cheers,

Pierre

**Comment by Bounciness** [comment]
Hi Pierre,

Thanks a lot for pointing this out, I'll fix the compatibility issue.

-Ben

**Comment by psalvy** [comment]
Hi Ben,

My pleasure ! Shall I wait for your fix before submitting my PR ?

Cheers,

Pierre
