### ISSUE TITLE
Duplicate fastcore.m function

### ISSUE THREAD

**Issue by laurentheirendt** [opencobra/cobratoolbox#515]
@jacekwachowiak just discovered that in PR #447, `fastcore.m` has been added although an existing function `fastcore.m` was already present.

- [original version](https://github.com/opencobra/cobratoolbox/blob/develop/src/dataIntegration/transcriptomics/FASTCORE/fastcore.m)
- [new version](https://github.com/opencobra/cobratoolbox/blob/develop/src/dataIntegration/transcriptomics/fastcore.m)

@arichelle, may you have a look at that? Thanks.

cc: @rmtfleming, @tpfau, @syarra

**Comment by arichelle** [comment]
I see, the original one that i've submitted included in its core the definition of "expressionRxns" and "threshold" which are now defined in createTissueSpecificModel  then the lines 45 to 52 in the original have been removed for the new version ... it is the only difference between the two from the code part (just saw that the header function in the new one are not properly formatted...)

**Comment by laurentheirendt** [comment]
@arichelle, would you mind taking care of this? Thanks 👍

**Comment by arichelle** [comment]
You want that I update the header of the new version ?

**Comment by rmtfleming** [comment]
The original file should remain and a diff done to add functionality to it if necessary, otherwise delete the new duplicate one. Thanks.

**Comment by arichelle** [comment]
OK will do that

**Comment by arichelle** [comment]
I've update the files but src/dataIntegration/transcriptomics/fastcore.m need still to be removed as it seems like I cannot do it myself using devTools

**Comment by laurentheirendt** [comment]
Fixed by PR #517. Thanks @arichelle!
