### ISSUE TITLE
runTimeLimit in MILP problem

### ISSUE THREAD

**Issue by arichelle** [opencobra/cobratoolbox#532]
In PR #449, I have added an options to solveCobraMILP to return a solution when the time limit is reached. This options has been added only for gurobi, I think it could be interesting to add this functionality for every solvers that MILP can use.

**Comment by tpfau** [comment]
Well, From what I see, most solvers actually employ this already. But there is a bug in the function, where timeLimit actually gets dropped....

**Comment by akaviaLab** [comment]
Can this be closed, since it has been merged?

**Comment by laurentheirendt** [comment]
As far as I remember, #546  only addresses this issue partially. @tpfau?

**Comment by tpfau** [comment]
I would say it can be closed. Not all solvers do actually support timelimit (e.g. the timelimit parameter passed on to glpk seems to be ignored.) From what I saw, all versions solvers that do support it have a timelimit option set.

**Comment by laurentheirendt** [comment]
Alright, let's close it for now. Thanks, @arichelle, @akaviaLab, and @tpfau 👍
