### ISSUE TITLE
Thermodynamic Documentation

### ISSUE THREAD

**Issue by zappingseb** [opencobra/cobratoolbox#55]
Dear Coders of Cobra Thermo tools,

I would like to check the thermodynamic consistency of one of my knockout strains and the fluxes given by an FBA/FVA analysis. Therefore I'd need to check out the deltaG matrices for this specific strain to get the concentration differences for each reaction to keep my fluxes as predicted by the FBA. Could you help me to create my knockout strain model with the vonBertalanffy toolbox and restricting it to the q-vector proposed by my FBA?
Maybe you already created a documentation for the tools?

Thank you,

Sebastian

**Comment by huldash** [comment]
Dear Sebastian,
We are currently preparing a tutorial for von Bertalanffy. We expect to publish it on GitHub in a few weeks. In the meantime, I would be happy to help you get started using von Bertalanffy. We included instructions for installation and usage in the help text for the top level function setupThermoModel (type "help setupThermoModel"). We also included an example script which you can use as a template (cobratoolbox/thermo/vonBertalanffy/testing/testVonBertalanffy.m). Try using these resources and contact me at the email address below if you run into any problems.
Best wishes,Hulda
--Hulda S. Haraldsdóttir, Ph.D.-----------------------------------------------------------------Research associate,Systems Biochemistry Group,Luxembourg Centre for Systems Biomedicine,University of Luxembourg,Campus Belval,7, avenue des Hauts-Fourneaux,Esch-sur-Alzette,Luxembourg,L-4362.-----------------------------Mobile:  +352 661 228 191Office: +352 466 644 6228wwwen.uni.lu/lcsb/people/hulda_haraldsdottirwwwen.uni.lu/lcsb/research/systems_biochemistry-----------------------------------------------------------------

Date: Fri, 26 Jun 2015 08:22:18 -0700

**Comment by zappingseb** [comment]
Dear Hulda,

Thank you for your answer.
Actually I downloaded the most recent version of MarvinBeans and your parser for cxcalc is not working with cxcalc 15.6.15.0. I created a parser for this problem that works perfectly with your estimate_pKa function. Can we maybe bring these two together?
Anyhow, it is not possible to estimate pKa for H+ and H2. So these had to be thrown out before, which was not implemented, yet.
I was also able to combine the 2007 publication of Henry et al with your toolbox to get the restrictions for the metabolite concentrations due to directional restriction of each reaction. This could be integrated, too.
If you need any help for the documentation, please tell me, as I worked through nearly all parts of your code already.

Cheers,

Sebastian

-- 
M.Sc. Sebastian Wolf
Wissenschaftlicher Mitarbeiter
Technische Universität München
Fakultät für Maschinenwesen
Fachgebiet für Systembiotechnologie
Boltzmannstr. 15
85748 Garching
Tel: +49.89.289.15747
Fax: +49.89.289.15766

**Comment by huldash** [comment]
Dear Sebastian,
Thank you for your efforts to improve von Bertalanffy. Can you please submit a pull request with your updates? I will merge them with the master version of the cobra toolbox.
I may contact you later for help with the documentation. Thank you for the offer.
Best,Hulda


Date: Wed, 8 Jul 2015 01:37:36 -0700

**Comment by laurentheirendt** [comment]
@rmtfleming , we need your input here. Thanks.

**Comment by rmtfleming** [comment]
Yes, it is on my radar.

**Comment by laurentheirendt** [comment]
Closing as a [tutorial](https://github.com/opencobra/cobratoolbox/tree/master/tutorials/analysis/vonBertalanffy) is now available. 

Thanks everyone! 👍
