### ISSUE TITLE
relaxFBA doesn't give minimal relaxation

### ISSUE THREAD

**Issue by tpfau** [opencobra/cobratoolbox#551]
I tried to test relaxFBA on a small model (basically:
```
-> A -> B -> C ->
        |    ^
        v  /
        D
```
setting the lower bound of B -> D  to 2, the lower bound of B -> C to 2 and the upper bound of C -> to 2 as well, (which gives an infeasible solution).
Now, relaxFBA indicates, that it minimizes the number of alterations needed to make this problem feasible. 
However, when running relaxFBA, I get an increase of the upper bound of C-> by 998 and decreases of the lower bound of B->D and B -> C by 1002 as minimal solution which is (quite obviously) not the minimal number of interventions (which would be just increasing the upper bound of C -> to something above 4 or decreasing either of the lower bounds to something <= 0. 

Anyone with a better grasp on relaxFBA an idea what is going wrong here?

**I hereby confirm that I have:**

- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

**Comment by rmtfleming** [comment]
please post here your script

**Comment by tpfau** [comment]
```Matlab
initCobraToolbox
changeCobraSolver('gurobi','all')
rxnForms = {' -> A','A -> B','B -> C', 'B -> D','D -> C','C ->'}
rxnNames = {'R1','R2','R3','R4','R5', 'R6'};
model = createModel(rxnNames, rxnNames,rxnForms)
model.lb(3) = 1;
model.lb(4) = 2;
model.ub(6) = 2;
res = relaxFBA(model)
```

**Comment by rmtfleming** [comment]
>> model = createModel(rxnNames, rxnNames,rxnForms)
Warning: Metabolite A[c] not in model - added to the model 
> In addReaction (line 276)
  In createModel (line 139) 
Error using xlsread (line 121)
File name must be specified.
Error in getDefinedFieldProperties (line 131)
    [~,~,raw] = xlsread(fileName,'Programatic Specification');
Error in getRelevantModelFields (line 98)
    fields = getDefinedFieldProperties();
Error in updateRelevantModelFields (line 57)
fields = getRelevantModelFields(model, type, originalSize);
Error in addMetabolite (line 211)
newmodel = updateRelevantModelFields(model,'mets');
Error in addReaction (line 277)
        model = addMetabolite(model,metaboliteList{i},metaboliteList{i});

Error in createModel (line 139)
    model = addReaction(model,{rxnAbrList{i},rxnNameList{i}},metaboliteList,stoichCoeffList,...

**Comment by tpfau** [comment]
This is an error, that was fixed on the latest devel tree (which was not yet merged with master), and arose from a specification file not being present on the path. If you add docs/source/notes to your path that error is resolved.

**Comment by laurentheirendt** [comment]
FYI: The above code runs with the latest version.

**Comment by tpfau** [comment]
@laurentheirendt I assume you are referring to my code snippet not relaxFBA, which still gives a solution with 3 altered bounds instead of one.

**Comment by rmtfleming** [comment]
I can reproduce this issue. Thanks for the alert. Trying to debug it now.

**Comment by laurentheirendt** [comment]
@tpfau, yes, I was referring to the code snippet above.

**Comment by marouenbg** [comment]
problem solved. just add
`relaxOption.nbMaxIteration = 10000;`
`res = relaxedFBA(model,relaxOption)`
I added an iteration limit warning in the code.

the proposed solution would be to decrease c by 998, which is of minimal cardinality. As for the relaxation value, one can run fva on the feasible model and take the lower bounds.

**Comment by marouenbg** [comment]
`relaxOption.exchangeRelax = 2` would give a minimal set on the exchanges which is c in the case.

**Comment by rmtfleming** [comment]
@tpfau, I think I meant to alert you to this issue.

**Comment by tpfau** [comment]
true this can be closed.
