### ISSUE TITLE
buildRxnGeneMat vs removeUnusedGenes

### ISSUE THREAD

**Issue by arichelle** [opencobra/cobratoolbox#580]
buildRxnGeneMat return a Matrix of dimension [length(genes) X length(rxns)]

then when we call the line 25 of removeUnusedGenes
genesToRemove = sum(model.rxnGeneMat) == 0;

it gives you the indices of rxns and not of the genes to remove...

**Comment by laurentheirendt** [comment]
@tpfau, may you have a look at this issue? Thanks!

**Comment by tpfau** [comment]
That's my fault.
I'm working on a correction.

**Comment by tpfau** [comment]
corrected, thanks for spotting it.
