### ISSUE TITLE
typo in optimizeCbModel?

### ISSUE THREAD

**Issue by dayena** [opencobra/cobratoolbox#619]
Hello, 
is "Support for coupling C*v<=d" not supposed to be "C*v>=d", as well as for the assumptions within the function optimizeCbModel? 

**I hereby confirm that I have:**

- [x] Tried to solve the issue on my own
- [x] Retried to run my code with the latest version of The COBRA Toolbox
- [x] Checked that a similar issue has not already been opened

**Comment by syarra** [comment]
@dayena, was this solved or clarified?

**Comment by laurentheirendt** [comment]
Clarified offline. Thanks everyone.
