### ISSUE TITLE
model.rev & old model fields

### ISSUE THREAD

**Issue by rmtfleming** [opencobra/cobratoolbox#624]
@tpfau please can you amalgamate the function to update model fields with a new one to automatically run through a .m file and replace model.rev with a boolean derived from model.lb and model.ub?
The idea would be to have a 'forwardCompatibility' folder where we put functions to bring models and functions uptodate?

**Comment by tpfau** [comment]
I don't think this can be done automatically, as the usage syntax is not always clear.
There are situations, where a temporary .rev field is generated that is later used for export as reversible indicator and might differ from the lb (depending on the use). 
Also, we can't rely on always having "model.rev", there are regularly output struct names which differ modelOut.rev, KEGG.rev etc... 
So I don't think functions can be done automatically. This is (imo) where extensive testing would be necessary to see if the function works with a new style model, and if not check the reason/adjust the function). 
Doing it automatically can screw up more than it might help, and can, worst case, lead to undetected mistakes, that alter already difficult to interpret results without failing.

**Comment by tpfau** [comment]
As long as noone reintroduces the field, .rev is removed from the current system.
As for the folder:
the only function necessary should be "convertOldStyleModel", which is called when loading a model using readCbModel from a mat file, and as such should ensure, that models loaded by the Toolbox (and not via load) adhere to the current standard.
