### ISSUE TITLE
incorrect model path in relaxFBA

### ISSUE THREAD

**Issue by marouenbg** [opencobra/cobratoolbox#688]
Model path is local in relaxFBA [tutorial](https://github.com/opencobra/cobratoolbox/blob/master/tutorials/relaxFBA/tutorial_relaxFBA.m#L89). If the model is available in the CBT, I would change the path.

**I hereby confirm that I have:**

- [ x] Tried to solve the issue on my own
- [ x] Retried to run my code with the latest version of The COBRA Toolbox
- [x ] Checked that a similar issue has not already been opened

**Comment by laurentheirendt** [comment]
Discussed internally. Thanks @marouenbg.
