### ISSUE TITLE
oldindices variable used before it is defined

### ISSUE THREAD

**Issue by snmendoz** [opencobra/cobratoolbox#723]
*I tried to run the tutorial for fastgapfill and I got the following error:
Undefined function or variable 'oldindices'.

Error in mergeTwoModels (line 101)
                modelNew.(fields1{i})(newindices1) = model1.(fields1{i})(oldindices);

Error in generateSUXComp (line 68)
    [modelExpanded] = mergeTwoModels(modelExpanded,KEGGComp,1);

Error in prepareFastGapFill (line 77)
MatricesSUX = generateSUXComp(consistModel,dictionary, filename,blackList,listCompartments);

Error in runGapFill_example (line 76)
    tic; [consistModel,consistMatricesSUX,BlockedRxns] = prepareFastGapFill(model);*

**I hereby confirm that I have:**

- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

**Comment by laurentheirendt** [comment]
Fixed in PR #832. Thanks @snmendoz for reporting.
