### ISSUE TITLE
lusolMex64bit git submodule

### ISSUE THREAD

**Issue by aebrahim** [opencobra/cobratoolbox#76]
When I run `git submodule update`, I get the following error message:

`No submodule mapping found in .gitmodules for path 'external/lusolMex64bit'`

**Comment by mdejongh** [comment]
This should take care of it:

git rm --cached external/lusolMex64bit

**Comment by syarra** [comment]
@aebrahim solved?

**Comment by syarra** [comment]
Closing this issue!
