### ISSUE TITLE
Missing file in rBioNet

### ISSUE THREAD

**Issue by fplanes** [opencobra/cobratoolbox#777]
We have tried to run the tutorial of rBioNet, but we found problems with the function rBioNetSettings.

The function requires a pre-existing rBioNetSettingsDB.mat file, which we have not found, neither in the tutorial folder nor in the source code folder.

Without rBioNetSettingsDB.mat file, we can not continue testing the tutorial.

**I hereby confirm that I have:**

- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

**Comment by laurentheirendt** [comment]
cc: @stefaniamagg

**Comment by stefaniamagg** [comment]
I'll add a part that creates & deletes the file in the tutorial, this file sometimes causes issues when it's left in multiple places in the Matlab paths. I'll see if I can update rBioNet too to deal with this file.

**Comment by laurentheirendt** [comment]
Thanks @fplanes for reporting this and thanks @stefaniamagg for fixing this! 🎉
