### ISSUE TITLE
Bugs in tutorial sparse_FBA_freeATPtest

### ISSUE THREAD

**Issue by fplanes** [opencobra/cobratoolbox#778]
We have problems running the tutorial sparse_FBA_freeATPtest.

The first step of the tutorial is to load Recon3 or other Recon:
if ~exist('modelOrig','var')
    filename='Recon1.0';
    %filename='Recon2.0';
    %filename='Recon2.0model';
    %filename='Recon2.04model';
    %filename='HMR2.0'
    %filename='Recon2.2model';
    %filename='Recon3.0';
    %filename='Recon3.0model';
    directory='~/work/sbgCloud/programReconstruction/projects/recon2models/data/reconXComparisonModels';
    model = loadIdentifiedModel(filename,directory);
    model.csense(1:size(model.S,1),1)='E';
    modelOrig = model;
else
    model=modelOrig;
end

The main problem is that Recon1.0 is not available in cobratoolbox/test/models. Also the directory variable is incorrect.

In addition, we have found a problem in the following line of code: 
fprintf('%6s\t%6s\n','#mets','#rxns'); fprintf('%6u\t%6u\t%s%s\n',nMet,nRxn,' totals in ', model.modelID)
as the field "modelID" is not present in all models, such as Recon2.04.

**I hereby confirm that I have:**

- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

**Comment by laurentheirendt** [comment]
Fixed in PR #820. Thanks @fplanes for reporting.
