### ISSUE TITLE
problem with Cobra testAll testModels (forwarded by Dr. Ronan M.T. Fleming)

### ISSUE THREAD

**Issue by longfeimao** [opencobra/cobratoolbox#79]
Dear Dr. Fleming,

After installing Gurobi, and after initializing Cobra, I run testAll. This gives an error message somewhere half way. I found out that the problem is with testModels. I have noticed three things with this:
- ```
       The folder testModels did not exist with previous versions of Cobra.
  ```
- ```
       testModels is not a function, like the functions in the other testing folders
  ```
- ```
       the second line of testModels.m states “if 1 %by default, do not run this script with testAll”.
  ```

**Comment by longfeimao** [comment]
Dear Dr. Silvia Wognum

Thank you for pointing out the issue to us. We have fixed it and updated the COBRA toolbox :)

Best wishes 
 
Longfei Mao, Ph.D.
-----------------------------------------------------------------------------------
Research Associate (Collaborateur Scientifique)
Systems Biochemistry Group,
Luxembourg Centre for Systems Biomedicine 

UNIVERSITY OF LUXEMBOURG
CAMPUS BELVAL

House of Biomedicine II 
6, avenue du Swing 
L-4367 Belvaux

T +352 46 66 44 5514
F +352 46 66 44 35514
-----------------------------------------------------------------------------------
 
http://wwwen.uni.lu/lcsb/research/systems_biochemistry
 
longfeimao99@gmail.com
longfei.mao@uni.lu
www.lcsb.lu
----------------------------

**Comment by syarra** [comment]
@longfeimao Closing?
