### ISSUE TITLE
checkDuplicate in addReaction seems to be set to 1

### ISSUE THREAD

**Issue by akaviaLab** [opencobra/cobratoolbox#795]
*Please include a short description of problem here*
The documentation for addReaction says that checkDuplicate default is set to false.
However, line 164 
parser.addParameter('checkDuplicate',1, @(x) isnumeric(x) || islogical(x));
sets checkDuplicate as 1.
This is problematic when adding lots of reactions, since lines 307-308 check for duplicates and take most of the running time of the function. 

I'm not submitting a pull request, since my git tree is messed up right now, and I'm trying to solve it.

**I hereby confirm that I have:**

- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

**Comment by laurentheirendt** [comment]
@akaviaLab, thanks for reporting this. It would be great if you could submit a PR for this 🎉

**Comment by laurentheirendt** [comment]
Closing as fixed by PR #835. Thanks @akaviaLab 👍
