### ISSUE TITLE
initCobraToolbox crashes Matlab 2016b

### ISSUE THREAD

**Issue by stefaniamagg** [opencobra/cobratoolbox#802]
Running initCobraToolbox frequently crashes Matlab 2016b on my computer (Windows). It is not a consistent issue - the function usually runs without issues.

According to the matlab crash dump file, it seems to be connected to a MEX file. Final lines of the matlab crash dump file (attached):

"This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.

If this problem is reproducible, please submit a Service Request via:
    http://www.mathworks.com/support/contact_us/

A technical support engineer might contact you with further information.

Thank you for your help."

[matlab_crash_dump.txt](https://github.com/opencobra/cobratoolbox/files/1156257/matlab_crash_dump.txt)

**I hereby confirm that I have:**

- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

**Comment by laurentheirendt** [comment]
May you post here the contents of your `startup.m`? Thanks.

**Comment by almut-heinken** [comment]
Hello,
I get a similar error. Attached is the Matlab crash output.
[initCobraToolbox_crash.txt](https://github.com/opencobra/cobratoolbox/files/1158839/initCobraToolbox_crash.txt)

**Comment by laurentheirendt** [comment]
@stefaniamagg  and @almut-heinken, this issue is difficult to reproduce, and we need more information from you. 

May you run after a clean start of MATLAB and **without** running `initCobraToolbox`:
```Matlab
>> changeCobraSolver('ibm_cplex')
>> Cplex('fba')
```
and print the output here?

**Comment by almut-heinken** [comment]
I entered changeCobraSolver('ibm_cplex') and it crashed Matlab (2016b) before I was able to enter the second command.

**Comment by stefaniamagg** [comment]
For me,
>> changeCobraSolver('ibm_cplex')

 > IBM ILOG CPLEX interface added to MATLAB path.

...and then Matlab crashed.

**Comment by laurentheirendt** [comment]
This is a problem with the local installation of CPLEX. 

May you uninstall CPLEX, re-install it, and try running the above commands above? Make sure that you check `Update the PATH variable` during the installation of CPLEX (this is the default).

For now, I just can't reproduce this behaviour. Thanks.

**Comment by shjchan** [comment]
Hi @stefaniamagg , @almut-heinken , please make sure to install the newest cplex 12.7.1. There is a known issue that most versions before 12.7.1 will cause Matlab R2016b crash. I have experienced this before.

https://www.ibm.com/developerworks/community/forums/html/topic?id=0ed51b80-5898-4ccc-84f7-ce8ed2dca697&ps=100

**Comment by stefaniamagg** [comment]
Hi @shjchan, I have cplex 12.7.1. The issue occured only after installing 12.7.1

**Comment by almut-heinken** [comment]
Hi @shjchan, I am also using 1.2.7.1 and Matlab 2016b only crashes since I installed it. The previous version caused difficulties in solving models, but no crash.

**Comment by laurentheirendt** [comment]
The incompatibility between `Matlab R2016b` and `CPLEX 12.7.0-` is known and already taken care of in `changeCobraSolver()`. This looks more like an issue with the installation of the solver itself. 

@shjchan, are you able to reproduce this behaviour?

**Comment by shjchan** [comment]
I get no problem in calling cplex 12.7.1 in Matlab R2016b but I am using mac. 
It's probably a problem in windows. In the forum someone using windows also reported the crash by cplex 12.7.1. Sounds like in 12.7.1 they fixed the problem in mac and linux but created another problem in windows...

**Comment by laurentheirendt** [comment]
Possible, although I cannot reproduce this on `Windows 7` and `CPLEX 12.7.1.`. Let's wait till @almut-heinken and @stefaniamagg reinstalled the solver.

**Comment by stefaniamagg** [comment]
Thanks @laurentheirendt , the re-installation worked!

>> changeCobraSolver('ibm_cplex')

 > IBM ILOG CPLEX interface added to MATLAB path.

ans =

  logical

   1

>> Cplex('fba')
     
ans=
     
   Cplex handle
     
   Properties:
      Model: [1x1 struct]
      Param: [1x1 struct]
      DisplayFunc: @disp
     
   Methods, Events, Superclasses
>> 

My (very detailed) steps:
1. Unistalled cplex 12.6.3
2. Start Matlab and run changeCobraSolver('ibm_cplex') to see if that fixed the issue (it didn't)
3. Unistall cplex 12.7.1
4. Restart computer
5. Install 12.7.1, prompted to install Microsoft Visual C++ 2013
6. Downloaded and installed Microsoft Visual C++ 2013 (x64)
7. Finish installation of cplex 12.7.1
8. Restart computer
9. Start Matlab and run changeCobraSolver('ibm_cplex')
-> Success!

**Comment by laurentheirendt** [comment]
Great @stefaniamagg 🎉 

@almut-heinken, if you confirm that these steps work, I will add them to FAQ.

**Comment by almut-heinken** [comment]
@laurentheirendt  Same here, installing Microsoft Visual C++ 2013 (x64) (https://www.microsoft.com/en-US/download/details.aspx?id=40784) did the trick. I now get 
changeCobraSolver('ibm_cplex')
IBM ILOG CPLEX interface added to MATLAB path.

ans =

  logical

   1

**Comment by laurentheirendt** [comment]
Awesome. I will add this to the FAQ. Great that we solved this issue 👍 .

**Comment by stefaniamagg** [comment]
Unfortunately, this issue is not solved for me yet. Matlab 2016b still crashes occasionally when running initCobraToolbox or changeCobraSolver('ibm_cplex'). It is not consistent for either of the two commands, sometimes it runs fine. Just in the last 15 minutes I ran the following commands in this exact order:

```
initCobraToolbox -> CRASH
(restart matlab)
initCobraToolbox -> CRASH
(restart matlab)
changeCobraSolver('ibm_cplex') -> RAN FINE
Cplex('fba') -> RAN FINE
initCobraToolbox -> RAN FINE
(restart matlab)
initCobraToolbox -> RAN FINE
changeCobraSolver('ibm_cplex') -> CRASH
```

**Comment by laurentheirendt** [comment]
@stefaniamagg, this seems to be an issue related to the local system's configuration. Let's look at that offline.

**Comment by laurentheirendt** [comment]
On Windows 10, [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) must be installed.

**Comment by cjos238** [comment]
@laurentheirendt I have both of those installed on my system (2013 and 2015). I still have this issue persisting. The Issue is sometimes the MATLAB crashes and sometimes it doesn't. Has this issue been resolved yet? Any suggestions?

**Comment by laurentheirendt** [comment]
@cjos238, we implemented a [compatibility matrix](https://github.com/opencobra/cobratoolbox/blob/master/docs/source/installation/compatMatrix.md) that should resolve these issues. Are you using the latest version?

**Comment by cjos238** [comment]
I don't think it is the latest version but I am using it locally, but fairly recent (maybe 1 or 2 months ago). I will try and see what changes have been made to the `initCobraToolbox`

**Comment by laurentheirendt** [comment]
@cjos238, the feature of the compatibility matrix has been added only recently. I would recommend updating. Thanks.

**Comment by almut-heinken** [comment]
@laurentheirendt Unfortunately, I am experiencing the same issue again with initCobraToolbox frequently crashing Matlab. I reinstalled Microsoft Visual C++ 2013 (x64) but that did not help.

**Comment by tpfau** [comment]
I'm not sure, whether we have any possibility to solve this. 
Maybe reporting this crash to both IBM and mathworks might be better, as they can actually test code changes. The only thing we could do, would be to deactivate cplex on Windows/Matlab2016b, but since it seems to work for some and only crashes irregularily, I'm not sure, whether thats the way to go.
