### ISSUE TITLE
checkObjective

### ISSUE THREAD

**Issue by swognum** [opencobra/cobratoolbox#82]
When running the first tutorial examples of Orth with the Ecoli core model, I get the following error message when calling checkObjective(model):

Error using fprintf
Function is not defined for sparse inputs.

Error in checkObjective (line 29)
                    fprintf('%6.4g\t\t%s\t\t%i\t%s\t%i\n',Sij,model.mets{objMetInd(m)},objMetInd(m),model.rxns{objRxnInd(n)},objRxnInd(n))

**Comment by tpfau** [comment]
I just submitted a pull request to update the function. Seems like it wasn't used for quite some time and still assumed that the S Matrices are full matrices instead of sparse matrices. 
So this should be resolved as soon as the pull request is merged.

**Comment by syarra** [comment]
@tpfau  and @swognum, is this solved?
If it is, please close the issue.

**Comment by tpfau** [comment]
Should be. But since I didn't open the issue I can't close it.

**Comment by laurentheirendt** [comment]
Closing, as fixed by https://github.com/opencobra/cobratoolbox/pull/97.

Thanks @tpfau .
