### ISSUE TITLE
grRules is optimal is some functions, mandatory in others

### ISSUE THREAD

**Issue by akaviaLab** [opencobra/cobratoolbox#825]
grRules is not created when reading SBML, and creategrRulesField states that the grRules field is optional.
However, certain functions like buildRxnGeneMat, updateGenes, changeGeneAssociation, findOrphanRxns, removedUnusedGenes, addReactionGEM, etc... assume that model.grRules exists and use it for their function.

I think that
1) either SBML should create grRules
2) readSBML should call creategrRules after reading the file
3) the functions that assume that grRules exist should be modified to use rules

I'm tagging @tpfau and @laurentheirendt, since I've think you've updated/created many of these functions. If there's a decision to go with 3, I can go over the code and modify it as appropriate.

Thanks!
  
**I hereby confirm that I have:**

- [X] Checked that a similar issue has not already been opened

**Comment by tpfau** [comment]
Personally, I vote for 3, as rules is the field that contains the programmatic version of the GPR associations, with a defined syntax while grRules depends a lot on the names of the genes.

**Comment by tpfau** [comment]
This should be solved and can (imo) be closed)

**Comment by akaviaLab** [comment]
Confirm solved, closing issue
