### ISSUE TITLE
COBRA update initialisations error updateCobraToolbox

### ISSUE THREAD

**Issue by smsinks** [opencobra/cobratoolbox#831]
*Please include a short description of problem here*

What does the error below mean? I have tried all I can, check online... No explanation. 
Thanks

>> updateCobraToolbox > Checking for available updates ... fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git command [<revision>...] -- [<file>...]' > The SHA1 of the last commit could not be retrieved.HEAD fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git command [<revision>...] -- [<file>...]' Warning: The name of the current feature (branch) could not be retrieved. > In updateCobraToolbox>getCurrentBranchName (line 171) In updateCobraToolbox (line 29)
**I hereby confirm that I have:**

- [] Tried to solve the issue on my own
- [] Retried to run my code with the latest version of The COBRA Toolbox
- [] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

**Comment by laurentheirendt** [comment]
@smsinks, may you submit the output here of:
```
>> generateSystemConfigReport
```
as well as the output of
```sh
$ cd cobratoolbox
$ git status
```
Please note that you can only update your version of the COBRA Toolbox when you don't have any local changes.

**Comment by laurentheirendt** [comment]
Closing, as error cannot be reproduced. The reported error is most likely related to local changes that have been made.

@smsinks, if you encounter further issues, please use our [forum](https://groups.google.com/forum/#!forum/cobra-toolbox). Thanks 👍
