### ISSUE TITLE
Bug in writeCbModel (documentation)

### ISSUE THREAD

**Issue by akaviaLab** [opencobra/cobratoolbox#836]
writeCbModel behavior does not match its documentation.

The documentation states (lines 36-37) that 
`%    % Write a model in the specified format with the given file name
%    outmodel = writeCbModel(model, 'format','mat', 'fileName', 'TestModel.mat')`

However, trying to run the following code
`finalFileName = 'foo'; 
writeCbModel(finalModel, 'format', 'mat', 'fileName', finalFileName);`

Gives the following error:
Error using writeCbModel (line 98)
No value was given for 'foo'. Name-value pair arguments require a name followed by a value.

It only works if you use the code `writeCbModel(finalModel, 'mat', finalFileName);`

I think this is because of the section in lines 51-75, and the fact that format and fileName are parser.addOptional instead of parser.addParameter. I'm not sure how to solve this to be a parameter and still work in old ways.
It is possible the simplest fix is just to fix the examples in the function.

**I hereby confirm that I have:**

- [X] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

**Comment by laurentheirendt** [comment]
Issue addressed in PR #891.

Thanks @akaviaLab for reporting!
