### ISSUE TITLE
Why has singleGeneDeletion.m been renamed to singleGeneDeletion_old.m ?

### ISSUE THREAD

**Issue by mdejongh** [opencobra/cobratoolbox#84]
Breaks pFBA (line 96).

**Comment by mlehoai** [comment]
Dear mdejongh,
We have added a new version of singleGeneDeletion to the repository. please let us know if there are any issues.
Regards,

Minh Le

**Comment by laurentheirendt** [comment]
Closing as not relevant anymore. `pFBA` is already CI-tested: PR #261 and `singleGeneDeletion_old.m` does not exist anymore.
