### ISSUE TITLE
Always the same objective function value (f)

### ISSUE THREAD

**Issue by ginlucks** [opencobra/cobratoolbox#86]
Hi all,

I am using recon2 model to test COBRA. I try to optimize the model for biomass reaction obtaining first solution. Then I set some constrains (such as no glucose import) and optimize the second model for biomass reaction.    When I compare two solutions the Objective Function Value f remain untouched as well as import level of glucose.     Why? 

these are the commands I used: 
run initCobraToolbox.m 
load('/home/matteo/Desktop/Gia/generic GEM/Recon2.v04.mat')
reconS=optimizeCbModel(modelR204, 'max')
reconNOGLU=changeRxnBounds(modelR204, 'EX_Glc(e)', 0, 'l') 
reconNOGLUS=optimizeCbModel(reconNOGLU, 'max')
printFluxVector(modelR204, [reconNOGLUS.x reconS.x], true, true)

in the resulting list it results : EX_glc(e)    -1  -1

**Comment by tpfau** [comment]
You have a typo in your code:
 reconNOGLU=changeRxnBounds(modelR204, 'EX_Glc(e)', 0, 'l') <-- it should be EX_glc(e) (lower case g).
However, this will not alter the growth rate, as the settings in Recon2 make glucose non limiting (there are plenty of other carbon sources available and the growth is more restricted by e.g. essential amino acids).

**Comment by laurentheirendt** [comment]
@tpfau , may we close this issue?

**Comment by tpfau** [comment]
I assume so, but without a further comment by @ginlucks I'm not sure.

**Comment by ginlucks** [comment]
Sure,  I solved the  problem.   Thanks.

Ottieni Outlook per Android<https://aka.ms/ghei36>



On Wed, Mar 15, 2017 at 8:42 AM +0100, "Thomas Pfau" <notifications@github.com<mailto:notifications@github.com>> wrote:


I assume so, but without a further comment by @ginlucks<https://github.com/ginlucks> I'm not sure.

**Comment by laurentheirendt** [comment]
Thank you @ginlucks .
