### ISSUE TITLE
readCbModel doesn't read rules correctly from SBML file

### ISSUE THREAD

**Issue by cjos238** [opencobra/cobratoolbox#861]
@akaviaLab 
**General description**
I am using iCEL1273 which can be accessed from WormFlux website (http://wormflux.umassmed.edu/). There are many reactions in the model which have such instances, at least 26 of them but maybe more. The previous version of "readCbModel" was able to read the gene reaction association without any errors and I was able to read the rules correctly.
Also, I was talking to the authors of iCEL1273 (they used cobrapy), and they had mentioned that gene reaction association of COBRA Toolbox on MATLAB has bugs and wasn't reading the SBML file correctly.
Please do let me know if there is any other information I can provide.

**Details**
I am reading the model from an XML/SBML file. The model can be downloaded from (http://wormflux.umassmed.edu/Downloads/iCEL1273.xml)
Specifically, the ids of the reactions for which rules are not being read correctly are as follows:
'RMC0004';'RMC0005';'RC03875';'RC04866';'RC04867';'RC02241';'RM03777';'RM04751';'RM01175';'RC00434';'RC08735';'RCC0053';'RC01206';'RC08183';'RC08177';'RCC0080';'RC08174';'RMC0132';'RC00548';'RC01010';'RCC0177';'RC02389';'RC02902';'RC02478'

**Example**
RM03777 ==> (acdh-7 or acdh-8 or acdh-10) or (acdh-1 or acdh-2)
----error----
RM03777 --> (x(468) | x(469) | **x(283)0)** | (x(283) | x(284))
----it should be----
RM03777 --> (x(468) | x(469) | x(466)) | (x(283) | x(284))

**Possible explanation and/or fixes**
_acdh-10_ is being read as _(acdh-1)0_

**I hereby confirm that I have:**
- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

Please do let me know if any other information is needed.

**Comment by akaviaLab** [comment]
Looking at your description in depth, it looks like what was solved in #845. I've downloaded the file from wormflux, and the rules aren't loaded at all, possibly due to a bug I'm looking into.

When you say previous version, can you tell me when you downloaded that, and when you downloaded the new version?

**Comment by cjos238** [comment]
Thanks for the link. I will see what changes I've to make and incorporate them. You are right, The file on the website is a bit erroneous too because new line characters are present when defining the gene association for a few reactions in the SBML file. This is so for the reactions with large gene association. Hope that helps.

The version I had earlier was downloaded sometime in November 2016, the version I am using now was downloaded yesterday.

**Comment by akaviaLab** [comment]
If you want to be able to read this SBML file, you need to change lines 56-58 in parseSBMLNotesField.m from
 if strcmp(strfields{1}, 'GENE_ASSOCIATION') || strcmp(strfields{1}, 'GENE ASSOCIATION')
        %Remove leading and trailing whitespace, and join the remaining strin again with the : separator
        grRule = strtrim(strjoin(strfields(2:end),':'));

To
 if strcmp(strfields{1}, 'GENE_ASSOCIATION') || strcmp(strfields{1}, 'GENE ASSOCIATION') || strcmp(strfields{1}, 'GPR_ASSOCIATION')
        %Remove leading and trailing whitespace, and join the remaining strin again with the : separator
        grRule = strtrim(strjoin(strfields(2:end),':'));

After this change, this specific file is loaded correctly.

I don't think this is valid SBML, but I'm tagging @tpfau to get his opinion. Thomas, if you think this is necessary, I can create a PR (or you can just add it to the function).

**Comment by laurentheirendt** [comment]
@akaviaLab, thanks for assisting here! 👍 

Would you mind putting in a PR with your proposed change? Thanks.

**Comment by laurentheirendt** [comment]
Thanks @akaviaLab!

**Comment by tpfau** [comment]
Just as a comment: I would claim this not to be valid COBRA Notes annotation. We can support it, but I would avoid supporting too many of these "Looks like COBRA but is not actually valid" annotations.
