### ISSUE TITLE
readCbModel/TranslateSBML doesn't recognize filepath correctly when using pop-up/dialog

### ISSUE THREAD

**Issue by cjos238** [opencobra/cobratoolbox#862]
**Description**
When using the pop-up version of the following command
_model = readCbModel;_
If the user points to the filepath using pop-up/dialog, the function continues to look in the current directory.

**Example**
Following error is generated, even after pointing to the file in "E:\Box\matlab\celegans\iCEL1273_2.xml"
_Error using TranslateSBML_
_File E:\Box\matlab\celegans\tissue_GFP\iCEL1273_2.xml does not exist on this path_

_Error in readSBML (line 31)_
_modelSBML = TranslateSBML(fileName,0,0,[1 1]);_

_Error in readCbModel (line 206)_
_model = readSBML(fileName,defaultBound);_

**Possible fixes**
It was implemented in the previous version of the function. 

**I hereby confirm that I have:**
- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

**Comment by laurentheirendt** [comment]
Fixed by PR #863. Thanks @cjos238 and @syarra
