### ISSUE TITLE
use -e option when calling babel in sdf2inchi.m

### ISSUE THREAD

**Issue by mpagni** [opencobra/cobratoolbox#876]
*Please include a short description of problem here*

In cobratoolbox/src/analysis/thermo/inchi/sdf2inchi.m: babel is called without the -e option. As a consequence, the produced list of InChIs is truncated after the first encounter of a "bad" MOL entry. With the -e option the list is processed to the end, only skipping the "bad" entries. 

I didn't evaluate the other system call to babel that are scattered in the code, maybe they should be fixed the same way?

Hope this help,

  Marco

**I hereby confirm that I have:**

- [X] Tried to solve the issue on my own
- [] Retried to run my code with the latest version of The COBRA Toolbox
- [] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

**Comment by laurentheirendt** [comment]
@mpagni, do you mind opening a pull request (PR) with your proposed enhancement? You can use the [MATLAB.devTools](https://github.com/opencobra/MATLAB.devTools) to easily submit your fix.

**Comment by laurentheirendt** [comment]
@jacekwachowiak, may you submit a PR with a fix for this issue? Thank you 👍

**Comment by jacekwachowiak** [comment]
Isn't babel called with the `options` optional variable?
`[inchi, metList] = sdf2inchi(sdfFileName, options)` - header

`[success,result] = system(['babel ' sdfFileName ' -oinchi' options]);` 
I don't know how it works - do you mean something like `babel-e...`?

**Comment by laurentheirendt** [comment]
The `-e` can actually be input using the `options` input argument in `sdf2inchi(sdfFileName, options)`.
