### ISSUE TITLE
testGenerateRules fails

### ISSUE THREAD

**Issue by dayena** [opencobra/cobratoolbox#887]
A pull request has been opened for the following minor issues:
It's Recon2 not Recon1 in testGenerateRules
generateRules fails to consider empty cells in model.rules 

However, the e coli model in testGenerateRules still fails.

**I hereby confirm that I have:**

- [x] Tried to solve the issue on my own
- [x] Retried to run my code with the latest version of The COBRA Toolbox
- [x] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

**Comment by laurentheirendt** [comment]
PR #888

**Comment by laurentheirendt** [comment]
Closing as issue cannot be reproduced. Thanks @dayena.
