### ISSUE TITLE
Error with generating mex file from cplexFVA.c (for fastFVA)

### ISSUE THREAD

**Issue by chaitrasarathy** [opencobra/cobratoolbox#946]
Hello,

I am trying to generate mex file from cplexFVA.c for fastFVA. I have installed CPLEX ILOG v12.7 Community Edition and I am running it on MATLAB R2016a.

The function generateMexFastFVA fails with the following error:

>> generateMexFastFVA
Warning: Duplicate directory name: C:\Program Files\MATLAB\R2016a\toolbox\stateflow\stateflow 
> In restoredefaultpath (line 52)
  In getCPLEXversion (line 25)
  In generateMexFastFVA (line 36) 
 > The CPLEX version has been determined as 1270.
MEX configured to use 'MinGW64 Compiler (C)' for C language compilation.
Warning: The MATLAB C and Fortran API has changed to support MATLAB
	 variables with more than 2^32-1 elements. In the near future
	 you will be required to update your code to utilize the
	 new API. You can find more information about this at:
	 http://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html.
Building with 'MinGW64 Compiler (C)'.
Error using mex
gcc: error: \-fexceptions: No such file or directory

Error in generateMexFastFVA (line 120)
    eval(['mex ' cmd]);

Please help me resolve it.

Thank you,
Chaitra

**Comment by laurentheirendt** [comment]
@chaitrasarathy, may you post this issue in [our forum](https://groups.google.com/forum/#!forum/cobra-toolbox)? Thank you.
